RecoRecoNi/Algorithm-Study

Programmers - 문제풀이/이모티콘 할인행사/jisu.py

15:55 -> 16:23 (28분 소요)
우선순위
- 1. 서비스 가입자 최대
- 2. 이모티콘 판매액 최대
핵심 조건
- 사용자는 자기 기준 비율보다 더 할인하는 이모티콘을 구매한다.
- 그렇게 구매한 이모티콘 가격의 합이 자기 기준 가격보다 높으면 이모티콘 플러스에 가입한다.
접근 방법
- 문제 제한이 복잡해서 시간 복잡도를 고려하기 어려웠으나, 전형적인 완전 탐색 문제라고 생각해서 완전탐색으로 접근
- 이모티콘마다 할인율(10, 20, 30, 40)이 다르다 -> 다르게 주어지는 건 할인율 뿐이다.
- 각 이모티콘에 할인을 적용하는 모든 경우의 수를 적용해보고 거기서 목적을 최대한 달성했을 때의 경우의 수를 찾자 (완전탐색)
``` text
주석을 길게 다니 리뷰할 때 보기 힘드실 것 같습니다..! 
가급적이면 코드 에디터 환경에서 복붙해서 보시는 것을 권장드립니다. 번거롭게 해드려 죄송합니다 ㅠㅠ..
```
- #26

[2023-05-21] jisu #26

---

Programmers - 문제풀이/아방가르드 타일링/jisu.py

17:30 -> ... 해결 x
[풀이 참고](https://magentino.tistory.com/172)
nx3 판에서 타일링 하는 경우의 수를 f(n)이라고 할때,
기본 적으로 f(n-1), f(n-2), ..., f(1) 이 채워져 있다고 가정하고, 각 경우에 대해 f(n)을 만들기 위해 추가로 고려해줘야 하는 경우를 생각해야한다.(특별 경우의 수라고 표현)
f(n-j)에서 f(n)을 만들기 위해 추가로 고려해줘야 하는 특별 경우의 수를 k(j)라고 할 때,
f(n) = k(1)f(n-1) + k(2)f(n-2) + ... + k(n-j+1)f(1) 이다.
이 때 f(n-1)에서 f(n)을 만드는 특별 경우의 수는 1
f(n-2) -> f(n) : 2
f(n-3) -> f(n) : 5
f(n-4) -> f(n) : 2
f(n-5) -> f(n) : 2
f(n-6) -> f(n) : 4
인데, f(n-7), f(n-8), f(n-9)는 각각 f(n-4), f(n-5), f(n-6)에서 1x3짜리를 가운데에 삽입해주면 만들어 낼 수 있으므로,
f(n-7) -> f(n) : 2
f(n-8) -> f(n) : 2
f(n-9) -> f(n) : 4
위와 같이 특별 경우의 수가 반복 되는 것을 확인할 수 있다.
특별 경우의 수 : i=4, 7, ..., i=5, 8, ...일 때 2, i=6, 9, ...일 때 4 가 반복됨을 활용해 점화식을 구하고,
각 SUM을 memoization하는 과정에서 업데이트 하는 방법으로 최적화 하면 다음과 같다.
```text
문제 이해도 오래걸렸고, 그렇다고 완벽하게 …
```

[2023-06-12] jisu #57

---

BOJ/큐/yerim.py

[백준 10845번: 큐 (Silver 4)](https://www.acmicpc.net/problem/10845)
풀이 시간: 19분
[접근 방법]
- queue 구현 시 연산 속도가 더 빠른 deque 사용
- push의 경우 띄어쓰기 후 숫자가 입력됨 => input 값을 split 함수를 사용해 리스트로 저장
- queue의 길이를 계산해야 하는 경우가 빈번하므로 미리 계산해둠
- push, size, empty 연산을 제외한 나머지 연산은 큐가 비어있는 경우 공통으로 -1을 출력하므로 그에 따라 조건 분할
- #58

[2023-06-14] yerim #58

---

BOJ/카드2/dohyun.py

풀이시간
- 약 5분
접근법
- 모든 동작 방식이 deqeue 로 구현가능
- 특정 조건 만족까지 반복되는 행위 -> 반복문/재귀로도 풀이 가능
회고
- 쉬웠던 것 같아서 재귀 풀이도 하나 넣어봤습니다!!
- 재귀문이 시간이 2배 이상 걸리는데 원래 그런걸까용?
- #69

[2023-06-18] dohyun #69

---

Programmers - 문제풀이/표 병합/jisu.py

- 표의 크기는 50x50, commands의 길이는 최대 1000이므로 구현만 해내면 크게 문제는 없을 것 같았음
- 소요시간
- 1차 접근 : 1시간
- 레퍼런스 참고 및 Union-Find 코드 이해 : 1시간
- 레퍼런스 적용 : 1시간
- 1차 접근
- MERGE 방식을 다음의 두 dict와 Merged Point를 관리하는 list를 활용하여 구현
- pv dict : key - point, value - value
- vp dict : key - value, value - set(points)
- merged_list : list(merge points list(merged points))
- 뭐라는지 모르겠죠? 저도 하다가 헷갈려서 엎었습니다.
- 레퍼런스 참고
- [레퍼런스](https://magentino.tistory.com/69)에서 MERGE & UNMERGE에 대한 KEY IDEA는 union&find임을 알게 됨
- [Union-Find 알고리즘](https://gmlwjd9405.github.io/2018/08/31/algorithm-union-find.html)
- Disjoint set을 표현하는 알고리즘인 Union-Find 방식을 이해하고 구현할 수 있게 됨
- 적용
- 주석과 위 레퍼런스 참고
- Disjoint Set의 표현 방식인 Union-Find를 이해해야 해당 풀이가 이해됩니다!
- #70

[2023-06-28] jisu #70

---

Programmers - 문제풀이/표 병합/yerim.py

[프로그래머스 - 표 병합](https://school.programmers.co.kr/learn/courses/30/lessons/150366)
- 소요 시간: 1시간 반 정도
- 접근 방법
- update, print는 쉽게 문제 그대로 구현
- merge 시 연결된 셀들을 집합으로 저장해두어 unmerge에 활용하려 했으나 실패
- 계속 merge, unmerge을 제대로 구현하는 것에서 어려움을 겪어 [블로그](https://wondev.tistory.com/153) 참고
- ufTable로 셀 위치를 따로 저장하는 테이블을 만들어 Union-Find로 merge, unmerge를 구현하는 것이 핵심
- #70

[2023-07-03] yerim #70

---

Programmers - 문제풀이/연속된 부분 수열의 합/yerim.py

- 소요 시간: 50분 + 30분(풀이 참고)
- 초기 접근 방법 => 시간 초과
- 시작 인덱스를 고정하고, 부분 수열의 길이가 1~n일 때 각 경우의 합을 모두 구함
- 시작 인덱스가 증가하는 만큼, 만들 수 있는 부분 수열의 개수는 짧아짐
- 부분 수열의 합이 k인 경우 해당 부분 수열 저장
- 부분 수열을 키로, 시작 인덱스와 마지막 인덱스를 값으로 하는 딕셔너리로 저장
- 여러 부분 수열을 길이, 인덱스 순으로 정렬해 첫 번째 원소를 답으로 리턴
- [참고한 풀이 방법](https://safetymo.tistory.com/14)
- 투 포인터를 사용
- 합이 작으면 오른쪽 포인터를 이동하고, 합이 크거나 같으면 왼쪽 포인터를 이동
- #81

[2023-07-10] yerim #81

---

Programmers - 문제풀이/연속된 부분 수열의 합/wooyeol.py

연속된 부분 수열의 합
https://school.programmers.co.kr/learn/courses/30/lessons/178870?
접근법
무슨 알고리즘으로 풀이 할 수 있을까? -> 투 포인터
- 정렬된 데이터와 연속된 부분 집합을 보았을 때 투 포인터 문제임을 직감 할 수 있었다.
- 테스트 케이스에 대해서 16,25번이 계속 틀려서 확인해보니 min_interval을 999995로 설정하였는데 값에 대한 범위이기에 1000001이 되어야했었다.
- 투 포인터의 전형적인 케이스는 일정 값을 기준으로 작거나 클때 start,end 포인트를 조정하는 방식이었는데 이번에는 start 지점을 증가시키는 방향을 고정하고 진행했어야 풀이가 진행될 수 있었다.
- 풀이 참고 (https://velog.io/@wodnr0710/프로그래머스-LV.2-연속된-부분-수열의-합)
- #81
테스트 1 〉 | 통과 (0.01ms, 10.1MB)
테스트 2 〉 | 통과 (0.01ms, 10.2MB)
테스트 3 〉 | 통과 (0.02ms, 10.2MB)
테스트 4 〉 | 통과 (0.42ms, 10.1MB)
테스트 5 〉 | 통과 (1.99ms, 10.4MB)
테스트 6 〉 | 통과 (4.07ms, 10.6MB)
테스트 7 〉 | 통과 (9.64ms, 11.6MB)
테스트 8 〉 | 통과 (19.42ms, 13.1MB)
테스트 9 〉 | 통과 (40.35ms, 16.6MB)
테스트 10 〉 | 통과 (148.79ms, 26.6MB)
테스트 11 〉 | 통과 (211.64ms, 43MB)
테스트 12 〉 | 통과 …

[2023-07-09] wooyeol #81 

---

Programmers - 문제풀이/연속된 부분 수열의 합/jisu.py

1시간 정도 소요
[제한조건]
5 <= len(sequence) <= 1,000,000
1 <= sequence <= 1,000
5 <= k <= 1,000,000,000
[idea]
0, 1, 2, ... i 번째 원소부터 누적합을 구한 후, 누적합이 k인 경우 찾기
이 때 기본 오름차순으로 정렬되어 있으므로 누적합은 항상 증가하는 방향이다.
또한 오름차순인 것에 힌트, 누적합이 k인 경우를 찾을 때 이진 탐색을 활용할 수 있다.
[누적합 활용]
sequence의 각 원소를 해당 원소까지의 누적 합으로 업데이트 한 후, i번째 원소 전까지의 누적합을 빼어
i번째부터의 누적합을 활용할 수 있다.
[이진 탐색]
i번째 인덱스 부터의 인덱스를 활용할 수 있다면, 오름차순으로 정렬되어있음을 활용해 k를 탐색하는 과정에서 이진 탐색(파라메트릭 서치)을 적용할 수 있다.
- #81 
- #0

[2023-07-09] jisu #81

---

Programmers - 문제풀이/연속된 부분 수열의 합/sumin.py

**<시간>**
20분
**\<input>**
- 5 ≤ sequence의 길이 ≤ 1,000,000
- sequence는 비내림차순으로 정렬
- 투포인터의 가장 기본적인 문제
- start, end 포인터를 0번 인덱스부터 시작해서 부분합을 확인한다.
- start부터 end까지의 부분합이 k와 같을 때까지 증가 end를 1 증가시킨다. (왜냐하면, sequence의 원소는 항상 자연수이기 때문에 가능)
- k는 항상 sequence의 부분 수열로 만들 수 있는 값이기 때문에 만들 수 없는 경우를 고려할 필요 없다.
- 부분합이 k와 같다면, 길이를 갱신해줘야 할 때만 갱신해주면 된다.
- 이후, 같은 과정을 start를 한 칸 씩 이동하면서 확인해주면 된다.
**시간복잡도 : O(n)**
- start를 0번 인덱스부터 마지막 인덱스까지 모두 확인한다.
- 내부 while문은 for문에 비례하여 n번 실행되는 것이 아니기 때문이다.("end"의 증가 횟수가 "start"의 증가 횟수와 독립적)
- #81

[2023-07-10] sumin #81

---

Programmers - 문제풀이/연속된 부분 수열의 합/dohyun.py

풀이시간
- 약 1시간 30분
접근법
- 비내림차순이므로 시작 인덱스가 고정되어 있으면 종료 인덱스는 특정 값까지의 합이 k 를 넘는이상 종료됨
- 따라서 시작 인덱스를 반복문으로 시작하기로 함
- 배열에 저장하지 않고 갱신 방식으로 답 저장 방식 채택
- 연산 속도 줄일 수 있음
- 처음에는 슬라이싱 연산을 매번해서 sum 을 했는데, 부분 수열의 합이고 업데이트 되는것은 인덱스들이기 때문에 매번 합을 할 필요가 없었음
- 슬라이싱 연산 시간복잡도 O(end-start) -> 합을 변수에 저장해서 갱신하자!
회고
- 생각보다 쉬운것 같다하고 풀었는데 테케에서 절반 정도 시간초과 나서 당황
- 그림을 다시 짜느라 고생했음 ... 처음부터 시간복잡도 고려를 꼼꼼히 해야하는데 아직 습관이 안된 것 같다 ㅠㅠ
- #81

[2023-07-10] dohyun #81

---

BOJ/덱/yerim.py

[백준 10866번: 덱 (Silver 4)](https://www.acmicpc.net/problem/10866)
- 풀이 시간: 10분
- 접근 방법
- 덱 자료형 사용
- 문제 그대로 구현
- #82

[2023-07-13] yerim #82

---

Programmers - 문제풀이/피로도/jisu.py

풀이 시작 : 2023-08-03 16:50
- 던전 개수가 최대 8개이므로 뭔 짓을 해도 될듯
- 완전 탐색으로 접근해보자
- permutation으로 모든 순서를 정해서 탐험 가능한 던전 수를 모두 구하는 방식
풀이 완료 : 2023-08-03 17:12
- 최소 피로도와 소모 피로도의 상관 관계를 생각해봤을 떄 그리디한 접근은 어려울 것 같음
- 여러 풀이들을 확인해봤지만 모든 케이스에서 성공한 그리디 풀이는 없었음
- #94

[2023-08-03] jisu #94

---

Programmers - 문제풀이/이중우선순위큐/jisu.py
Programmers - 문제풀이/이중우선순위큐/jisu_baekjoon.py

풀이 시작 : 2023.08.03 15:45
우선순위 큐에서 빈 큐가 아니라면 최대값, 최소값만 구할 수 있으면 된다.
이를 위해 큐를 최소힙으로 구현한다면 최소 값은 0번쨰 인덱스, 최대 값은 nlargest(1)로 구해낼 수 있다.
그렇다면 최소값을 삭제하는 연산은 O(1)에 가능할 것 같은데, 최대 값을 삭제하는 것은 O(n) 이상이 걸릴 것
될까..? 일단 해보자
풀이 완료 : 2023.08.03 16:06
- heappush(heap, value) : 삽입 시에 제자리 찾아가는 과정을 거침, 이진 트리 기반이므로 O(logn)
- heappop(heap) : 최소값 하나를 삭제 후 힙 구조에 맞춰서 인덱싱을 거침 O(logN)
- nlargest(m, heap) : heap에서 큰 순서대로 m개 찾아서 반환해줌, 복잡도는 힙의 요소가 n개라고 할 때 O(n+log(m))
이중 우선순위 큐 백준 버전 : 프로그래머스 문제와 동일하지만, 테스트 케이스에 대해 좀 더 엄격한 문제
풀이 시작 : 2023.08.06 21:25
- 동일하게 min heap으로 구현하되, 보다 효율적으로 최댓값을 삭제해야 함
- 접근 1 : minheap, maxheap을 관리하는 MinMaxHeap 클래스를 구현해서 해결해보기
- 문제는 한 쪽에서 pop 했을 때 다른 한 쪽은 어떻게 없앨꺼냐...
- 반대편 heap 맨 뒤에서 부터 탐색해서 없애보기? 맨 뒤에서 부터 있을 확률이 높으니까 조금 더 연산이 줄지 않을까? 안정적이지는 못 한 방법.
- 없앤다음에 heapify 해야함
- 시간초과...
- 접근 2 : 삽입된 …

[2023-08-03] jisu #93

---

Programmers - 문제풀이/타겟 넘버/jisu.py

풀이 시작 : 2023.08.09 13:03
- 순서를 바꾸지 않아도 된다 -> 덧셈 뺄셈 연산자만 바꿔가며 경우의 수를 판단
- 그리디한 접근은 어려울 것 같고(어차피 다 탐색해야함), 주어지는 수의 개수가 많지 않아서(20개) 완전탐색(dfs)으로 구현할 수 있을듯 함
- 모든 수를 순서대로 탐색해야하므로 가지 치기는 없고, 그냥 부호만 바꿔가며 가지를 뻗어나가기만 하면 될 것 같다.
풀이 완료 : 2023.08.09 13:22
- #96

[2023-08-11] jisu #96

---

BOJ/괄호의 값/jisu.py

풀이 시작 : 2023.08.13 23:31
- 문자열 길이는 최대 30이므로 O(N^2)이상도 가능할 듯함
- 열린 괄호('(', '[']))가 나오면 반환 값에 (2, 3) 을 곱해서 다시 재귀를 반복하는 방식으로 구현하면 될 듯 함
풀이 정지 : 2023.08.14 01:00
풀이 재개 : 2023.08.14 10:40
- 풀이 변경 : 재귀 없이 순회로, 괄호가 열렸을 때 값을 저장해서 풀이
- 닫힌괄호는 직전이 동일 열린괄호가 아닌 이상 배율을 적용하는 역할을 함 
- 열린 괄호가 중첩해서 나오면 배율 적용
- 닫힌 괄호가 나오면 
- 이전 braket이 올바른 열린 괄호이면 현자깨지 배율을 값에 더해줌 (곱의 법칙 활용)
- 배율 조정
- 올바른 괄호열인지 판단이 필요하므로, 스택을 활용해서 매번 올바른 괄호열인지 판단 후 예외처리
풀이 완료 : 2023.08.14 11:40 (풀이시간 : 2시간 30분)
- #110

[2023-08-14] jisu #110

---

BOJ/괄호의 값/dohyun.py

풀이시간
- 약 40분
접근법
- 문자열 길이 되게 짧음 -> 시간복잡도 신경쓰지말고 꼼꼼히 구현해보자
- 이전 풀이 문제(쇠 막대기)에서 스택 풀이를 제대로 이해못했지만, 비슷한 느낌인 것 같아 쇠 막대기 풀이 참고
- 올바르지 못한 괄호열은 어떻게 정의할까?
- ( 다음 ] 가 오면 땡
- [ 다음 ) 가 오면 땡
- 소괄호와 대괄호의 개수가 다르면 땡
회고
- 스택 풀이 이해하기!
- #110

[2023-08-14] dohyun #110

---

BOJ/빙산/jisu.py

풀이 시작 : 2023-08-16 10:20
- N과 M은 최대 300 -> O(N^2) 보다 훨씬 이상도 가능, 전형적인 그래프 탐색 문제로 접근
- 1년에 해당하는 time step 마다 모든 좌표에서 BFS를 실행
- 이 때 BFS가 처음으로 두 번 이상 실행되는 time step을 구하면 될 것 같다.
- 한 번 BFS를 돌릴 때마다 현재 방문 중인 빙산은 인접한 바다 방면만큼 줄이기
- 특정 빙산이 1 -> 0이 되는 경우 다음 빙산에서 해당 지점을 애초에 바다로 인식할 수 있으므로, 이동할 경로를 먼저 담고 빙산을 줄이자.
풀이 완료 : 2023-08-16 10:55
- #112

[2023-08-16] jisu #112

---

BOJ/불!/sumin.py

**풀이시간**: 35분
**\<input>**
1 ≤ R, C ≤ 1000
- R: 미로 행의 개수
- C: 열의 개수
이 문제의 경우 불과 지훈이가 동시에 이동하기 때문에, 이 처리를 어떻게 해줄 것인지가 관건인 문제다.
하지만, 불은 1분에 인접한 네 방향으로 모두 이동지만, 지훈이의 경우 한 칸 밖에 이동하지 못한다.
따라서 둘에 대해 각각의 BFS를 돌아 각 칸에 도착하는데 걸리는 이동 시간을 확인하면 된다.
불의 전파시간에 대한 BFS를 먼저 확인 후, 지훈이의 이동에 대한 BFS를 돌면 되는데 이 때 다음의 조건을 확인하면 된다.
- 지훈이가 도착할 예정시간보다 불이 해당 칸에 전파되는 시간이 더 짧은 경우(지훈이가 도착하면 이미 불이 붙어있기 때문에 탈출 실패)
**<시간복잡도>**
BFS 시간복잡도: O(R*C), 최대 1,000,000번 연산

[2023-08-16] sumin #111

---

BOJ/Z/sumin.py

**풀이시간**: 25분
**\<input>**
- 1 ≤ N ≤ 15
- 0 ≤ r, c < 2N
1. 함수의 정의
- 2^n x 2^n 배열에서 (r,c)를 방문하는 순서를 반환하는 함수
2. base condition
- n = 0일 때, return 0
3. 재귀식
- (r,c)가 1번 사각형일 때, return go(n-1, r, c)
- (r,c)가 2번 사각형일 때, return half*half + go(n-1, r, c-half)
- (r,c)가 3번 사각형일 때, return 2*half*half + go(n-1, r-half, c)
- (r,c)가 4번 사각형일 때, return 3*half*half + go(n-1, r-half, c-half)

[2023-08-18] sumin #113

---

BOJ/종이의 개수/wooyeol.py

종이의 개수
https://www.acmicpc.net/problem/1780
풀이시간 
08:30 ~ 09:30 + 13:30~14:44 (2시간 14분)
N(1 <= N <= 3**7, N은 3**k 꼴)
접근법
무슨 알고리즘으로 풀이 할 수 있을까? 재귀 / 분할 정복
문제에는 두 가지 조건이 주어진다. 첫 번째는 9개의 값이 같은 값이라면 그 종이는 하나
9개의 값이 다른 경우 그 종이는 각각 하나의 종이씩이다.
그렇기에 범위 내의 데이터가 모두 같을 경우와 같지 않을 경우를 검사하고 같지 않다면 
9개로 나눠서 다시 연산 진행 3**N 으로 주어지기에 3**(N-1)의 경우 다시 검사하여
9개로 나눠진 값이 각각 하나씩만 반환할 때까지 분할해서 정복한다.
풀이 참조 : https://velog.io/@yje876/python백준분할정복-1780-종이의-개수

[2023-08-18] wooyeol #114

---

BOJ/불!/dohyun.py

풀이시간
- 약 7시간 (공부하면서 같이 풀었습니다!!)
접근법
- 불의 좌표를 구해서 행렬 값을 번지는 불로 바꿔볼까? -> 시간복잡도 걸릴 것 같음
- 불의 좌표 구하고 행렬 값을 바꾸지말고 불 인덱스를 추가하자 -> 불에 닿으면 IMPOSSIBLE
- 그리고 불이나 벽이나 글로 못가는건 똑같음 -> 벽 인덱스도 추가
- 문제에서 보면 "불이 도달하기 전에" -> "불이 도착점에 도달하기 전에"
- 지훈이의 탈출 지점에 불이 더 빨리 도착하냐? 지훈이가 더 빨리 도착하냐? 를 계산하면 될것같음
- 계속 보다보니 예전에 잠깐 봤던 BFS 가 생각나서 BFS 알고리즘 코드는 인터넷에서 배꼈습니당 .. ㅎ 
- 혼자 BFS 를 짜다보니 도저히 감도 안오고 시간도 오래걸리고, 외우다시피 익숙해지는게 좋다고 해서 우선은 배꼈습니다!! 앞으로 연습 많이 할게요!!
회고
- 왜 틀렸다고 뜨는지 도저히 잘 모르겠어요 ,, ㅠㅠ 어디 때문에 안되는지 혹시 아시겠다면 말씀해주시면 정말 감사하겠습니다 !!!
- #111

[2023-08-16] dohyun #111

---

Programmers - 문제풀이/전화번호 목록/sumin.py

**풀이시간**: 10분
**\<input>**
- phone_book의 길이: 1 이상 1,000,000 이하
- 각 전화번호의 길이: 1 이상 20 이하
- 같은 전화번호가 중복해서 들어있지 않다.
1) 정렬 후 현재 확인하고 있는 번호가 다음 번호의 접두어인지 확인하는 방법
2) 해시를 이용해 특정 전화번호의 접두어가 다른 번호인지 확인하는 방법
**<시간 복잡도>**
1) O(nlogn)
2) O(nm): n은 전화번호의 총 개수, m은 최대
**<기타>**
이 외에 트라이로도 풀이 가능

[2023-08-21] sumin #136

---

BOJ/빙산/wooyeol.py
BOJ/빙산/wooyeol2.py

빙산
https://www.acmicpc.net/problem/2573
풀이시간
10:33 ~ 14:12 (풀이 실패) + 4시간 (풀이 성공)
접근법
무슨 알고리즘으로 풀이 할 수 있을까? BFS
시간 초과와 메모리 초과로 실패했습니다. -> 리뷰를 보며 다시 풀이를 진행하여 풀이해낼 수 있었습니다.
- 빙산 테이블을 만들면서 빙산의 위치를 덱에 기억시켜놓고 첫 요소를 기점으로 BFS로 진행합니다.
- BFS 연산을 거치며 해당 빙산 주변 바다의 갯수를 통해 빙산의 높이를 조절합니다.
- 하나의 빙산 덩어리는 첫 요소를 기점으로 BFS를 진행하였을 때 모든 요소를 탐색 할 수 있습니다. 
- 혹시라도 빙산의 위치를 저장시킨 덱의 요소를 다 검사하였을 때 한 번 더 BFS 탐색을 한다면 두 개의 빙산 덩어리가 발생하였다는 것 이므로 현재 연도를 반환
- 만약 BFS 연산이 일어나지 않았다면 0개의 덩어리라는 것이므로 0을 반환

[2023-08-16] wooyeol #112

---

Programmers - 문제풀이/네트워크/jisu.py

풀이 시작 : 2023-08-21 12:13
- 그래프 탐색 문제로 보이고 n도 200 이하이므로, 보통의 그래프 탐색 알고리즘(BFS, DFS)을 적용해도 될 것이다.
- 결국 전체 네트워크가 몇 덩어리로 나뉘어져 있는지를 알면 되므로, BFS를 적용해 탐색이 몇 번 일어나는지 확인하면 된다.
- 다만 주어진 인접행렬은 현재 두 컴퓨터가 연결되었다는 정보를 나타내므로, BFS탐색을 용이하게 하기 위해 각 컴퓨터가 연결 중인 다른 컴퓨터의 리스트를 따로 관리할 필요가 있다.
풀이 완료 : 2023-08-21 12:40 (풀이 시간 27분)
- 근데 풀이하다 보니 인접 행렬을 재구성 하는 과정 없이 풀이가 가능할 것 같다. 탐색 인덱스를 적절히 활용하면 될 것 같다. 
-> 인접 행렬을 그대로 활용한 풀이 추가
- camel -> snake

[2023-08-23] jisu #143

---

Programmers - 문제풀이/네트워크/dohyun.py

풀이시간
- 약 1시간
접근법
- N = 200 -> 시간 복잡도 크게 고려하지 않아도 될 것 같음 (각 배열을 고려해 N^2 해도 충분)
- 모든 컴퓨터를 탐색하여 연결 정보를 찾아야 함 
- 그래프 탐색 알고리즘(DFS/BFS)을 사용해야겠다라고 판단
- 제한 시간을 초과해서 답지를 봤습니다 .. ㅎ
회고
- DFS/BFS 유형은 매우 중요한데도 거의 손도 못대겠음 ㅠㅠ 해당 유형 문제 많이 풀어보기
- #143

[2023-08-23] dohyun #143

---

Programmers/압축/wooyeol.py

압축
https://school.programmers.co.kr/learn/courses/30/lessons/17684
풀이시간 22:30 ~ 23:00 | 23:53 ~ 00:27 (1시간 4분)
시간복잡도
O(n) - n은 msg의 길이(1~1000)
접근법
무슨 알고리즘으로 풀이 할 수 있을까? -> 구현
1. W(현재 입력) 값을 찾기
- 가장 긴 사전에 있는 문자열 w를 찾기
2. 가장 긴 W의 사전 인덱스 값을 answer에 삽입
3. W+C를 사전에 등록하기

[2023-08-28] wooyeol #144

---

Programmers/야근 지수/dohyun.py

풀이시간
- 1시간 30분
접근법
- 사전 시간복잡도 계산을 어떻게 해야하나..?
- 우선 works 의 길이로 확인해야한다고 생각 -> 20000 이하로 대략 O(N^2) 까지 가능?
- 야근 피로도 = sum(남은 일 작업량**2)
- 합의 최대최소를 구하는 문제 -> 고딩 때 배운 산술기하 생각남
- 산술기하평균의 등호 조건에 따르면 합의 최소값은 모든 원소가 같을 때! -> 평균값 및 몫과 나머지 활용
- 경계해야하는 것은 works 의 원소들이 몫보다 작으면 모든 원소를 같게할 수 없음
- 즉 "최대한" 같게하는 것이 관건 -> 해당 조건처리 필요
- 조건에 부합하는(값이 몫보다 큰) 애들만 몫과 나머지를 적절히 나누어주면 됨
회고
- 값이 몫보다 작은 경우를 생각하지 못해서 시간이 좀 오래 걸렸음
- 자꾸 테케에서 몇개가 오류가 나서 예제를 여러 개 생각해보니 반례 찾는것에 성공
- 주어진 예제 이외의 예제들도 만들어서 디버깅하는 습관 더 연습하기
- #145

[2023-08-28] dohyun #145

---

Programmers/N-Queen/jisu.py

풀이 시작 : 2023-08-28 10:30
퀸이 다른 말을 잡을 수 있는 경우
- 세로 같은 열에 있는 경우
- 가로 같은 열에 있는 경우
- 대각선 같은 열에 있는 경우
- 체스판을 순회하며 퀸을 놓는 경우와 놓지 않는 경우로 재귀한다.
- 이때 재귀를 진행하다 해당 위치에 퀸을 놓는 경우 위의 사항에 해당 된다면 해당 분기는 잘라내기(백트래킹)
- 체스판 순회가 끝날 때까지 퀸을 N개 놓으면 경우의 수 추가
풀이 중단 : 2023-08-28 11:00 (30분 경과)
풀이 재개 : 2023-08-28 13:55
- Hint : 어차피 NxN 체스판에서 한 row에 한 퀸 밖에 둘 수 없음
- 이러면 NxN Matrix를 구성 안하고, 길이 N의 리스트에 각 요소는 퀸이 위치한 column의 값을 가지게 두면 된다.
- 예를 들어 2x2 체스판이라고 가정 하고, (0, 0), (1, 1)에 퀸을 배치하면 [0, 1] 요런식
- 이러면 가로 제약조건은 자동 만족
- 세로 제약조건은 같은 열만 아니면 됨
- 대각선은 |현재 인덱스 - 비교 인덱스| == |현재 인덱스의 값 - 비교 인덱스의 값| 을 검사하면 됨
- 예를 들어 (0, 0), (1, 1)에 배치하여 [0, 1]인 경우
- |현재 인덱스 - 비교 인덱스| = |0 - 1| = 1
- |현재 인덱스의 값 - 비교 인덱스의 값| = |0 - 1| = 1
- 같으므로 대각선에 위치하는 것
- 풀이 완료 : 2023-08-28 15:45 (2시간 20분 소요)
- python3는 통과 못하고 pypy만 통과
- python3 통과시켜보고 싶었으나 실패, …

[2023-08-30] jisu #160

---

BOJ/N-Queen/wooyeol.py

N-Queen
https://www.acmicpc.net/problem/9663
풀이시간 
BaaaaarkingDog의 백트래킹 강의를 보고 풀이를 시작
00:05 ~ 01:20 (1시간 15분) - 풀이 참고
문제 조건
1 <= N <= 15
시간 복잡도 : O(n!)
접근법
무슨 알고리즘으로 풀이 할 수 있을까? -> 백 트래킹
- 퀸은 상하좌우와 대각선 방향 이동이 모두 가능합니다.
- 검사는 각 row를 기준으로 갯수를 확인해야한다.
- col이 같은 값은 체크
- 대각선을 검사하기 위해서는 x+y / x-y 의 값이 같은 경우는 체크
- 대각선은 왼쪽위에서 오른쪽 아래로 향하는 경우 (x,y)를 기준으로 x-y의 값이 같은 경우를 의미한다.
- 오른쪽 위에서 왼쪽 아래로 향하는 경우 (x,y)를 기준으로 x+y의 값이 같은 경우를 의미한다.

[2023-08-30] wooyeol #160

---

Programmers/암호 만들기/wooyeol.py

암호 만들기
https://www.acmicpc.net/problem/1759
풀이시간 
10:52 ~ 11:43 (49분)
문제 조건
3 <= L <= C <= 15
L개의 알파벳 소문자 (최소 한 개의 모음과 두 개의 자음)
시간 복잡도 : O(L x C)
접근법
무슨 알고리즘으로 풀이 할 수 있을까? -> 백 트래킹
- 주어진 알파벳을 정렬하고 방문한 알파벳은 표시를 해둔다.
1. 백트래킹을 구현하며 Base Condition(길이가 L과 같고 모음의 갯수가 0보다 크고 자음의 갯수가 1보다 클 경우)일 경우만 값을 출력
2. 백 트래킹을 위한 검사문들을 작성한다.
1. 중복을 허용하지 않고 알파벳 사전순일 경우만 확인하기 때문에 현재 담겨있는 알파벳보다 더 큰 인덱스 값만 검사한다.
2. 방문하지 않은 알파벳일 경우
2-1. 현재 위치를 방문 처리하고 해당 값을 Password에 넣은 뒤 자음과 모음 갯수를 업데이트한다.
2-2. 다음 자리 알파벳을 백 트래킹으로 찾는다.
2-3. 탐색된 알파벳을 방문처리를 해제하고 자,모음 갯수를 다시 업데이트 한다.

[2023-08-30] wooyeol #161

---

BOJ/N-Queen/sumin.py

**풀이시간**: 25분
**\<input>**
- N(1 ≤ N < 15)
- N X N인 체스판 위에 퀸 N개를 서로 공격할 수 없게 놓기 위해서는 각 행에 1개의 퀸을 놔야 한다.
- 퀸은 상하좌우, 대각선으로 움직이기 때문에 위에서부터 아래로 내려오며 퀸을 배치할 수 있는 곳에 배치해야 한다.
- 모든 경우의 수를 확인하되, 퀸을 둘 수 없는 칸(상하좌우, 대각선 칸에 이미 다른 퀸이 있는 경우)에 대해 처리하기 때문에 백트래킹으로 풀이가 가능하다.
1\) 같은 열인지 확인: 같은 col을 가질 때
2\) 같은 ↗ 대각선에 있는지 확인: row + col값이 같을 때
3\) 같은 ↘ 대각선에 있는지 확인: row - col값이 같을 때    
</br>
**<시간복잡도>**
열만 가지고 생각했을 때는 O(N!)일 수 있지만, 실제 백트래킹에서 가지치기가 빈번하게 발생하면 이보다 훨씬 시간복잡도가 줄어들기 때문에 제대로 파악하기 어려움

[2023-08-30] sumin #160

---

BOJ/암호 만들기/dohyun.py

풀이시간
- 약 1시간 20분
접근법
- 알고리즘에 따라 사전 시간복잡도가 많이 달라질듯 함
- 최소 한 개의 모음 / 최소 두 개의 자음
- 해당 조건을 잘 처리하는 것이 관건
- 암호가 이미 존재하므로 최소 한 개의 모음과 두 개의 자음이 입력으로 주어지긴 할 것 -> 예외처리 할 필요 X
- 문자열의 조합 -> itertools 모듈을 잘 활용해보자
- 걱정되는 것은 시간복잡도에 걸리지 않을까?
- 최악의 경우인 15 에도 15C10(조합) = 3003 이므로 문제없을 듯 함
- 정렬하는 과정이 많지만 최대 L (15이하) 길이의 정렬이므로 문제될 것 없음
회고
- 풀고나서 답을 보니 뭔가 운이 좋아서(?) 풀이가 가능했던 것 같은 기분 ...
- 물론 시간복잡도에 걸릴 것 같다는 생각이 들었다면 가능한 조합을 다 구하지는 않았겠지만, 그래도 정석적인 풀이(정형화 되어있는?)를 지향하기
- #161

[2023-08-30] dohyun #161

---

Programmers/주차 요금 계산/sumin.py

**풀이시간**: 20분
**\<input>**
- fees: 주차 요금 (fees의 길이 = 4)
- fees[0]: 기본 시간(분)
- fees[1]: 기본 요금(원)
- fees[2]: 단위 시간(분)
- fees[3]: 단위 요금(원)
- records: 자동차의 입/출차 내역 (1 ≤ records의 길이 ≤ 1,000)
- 시각, 차량번호, 내역
- 단순 구현!!
**<시간 복잡도>**
O(NlogN): 전체 코드 중 정렬이 가장 많은 시간 소요됨

[2023-09-06] sumin #182

---

Programmers/단어 변환/sumin.py

**풀이 시간**: 20분
**<입력, 제한사항>**
- 각 단어는 알파벳 소문자로만 이루어져 있음
- 각 단어의 길이는 3 이상 10이하, 모든 단어의 길이가 같음
- words에는 3개 이상 50개 이하의 단어가 있고, 중복되는 단어는 없음
- begin과 target은 서로 다름
- 변환할 수 없는 경우 0 return
**<풀이>**
begin 단어에서 target 단어까지 가는 최단경로를 찾기 위해서 BFS를 사용함(각각의 단어를 노드로 생각)
1. 시작 단어를 큐에 넣는다.
2. dist 배열에 {key: value}를 {각 단어: begin에서 해당 단어까지 걸리는 최단거리} 형태로 초기화한다.
3. 큐에서 하나의 단어씩 꺼내 다음 단어로 올 수 있는 단어만 깊이를 갱신한다. (이 때, dist 배열을 사용해 아직 방문하지 않은 단어에 대해서만 처리한다.)
- can_transform 함수를 통해 '한 번에 한 개의 알파벳만 바꿀 수 있습니다.' 조건을 만족하는지 확인
4. 만약 현재 단어가 target 단어라면 해당 단어까지의 깊이를 return 해준다.
5. 큐가 빌 때까지 다 돌아도 target 단어까지의 깊이를 return 하지 못한다면 해당 단어로 만들 수 없는 경우이기 때문에 0을 return 한다.
**<시간 복잡도>**
`O(N * K)`
- N: words 리스트의 길이(최대 50)
- BFS를 통해 words 리스트의 모든 단어를 한 번씩만 확인하므로 O(N)
- K: 단어의 길이(최대 10)
- can_transform 함수는 두 단어의 길이만큼만 비교하기 때문에 최대 …

[2023-09-08] sumin #184

---

BOJ/LCS/wooyeol.py

LCS
https://www.acmicpc.net/problem/9251
풀이 참조 : https://velog.io/@emplam27/알고리즘-그림으로-알아보는-LCS-알고리즘-Longest-Common-Substring와-Longest-Common-Subsequence
풀이시간
13:22 ~ 14:22(1시간 고민 후 풀이 참고)
문제 조건
문자열의 최대 길이는 1000
시간 복잡도 :
O(N * N) = O(N^2)
접근법
무슨 알고리즘으로 풀이 할 수 있을까? -> DP
점화식:
1. 문자열A, 문자열B의 한글자씩 비교해봅니다.
2. 두 문자가 다르다면 LCS[i - 1][j]와 LCS[i][j - 1] 중에 큰값을 표시합니다.
3. 두 문자가 같다면 LCS[i - 1][j - 1] 값을 찾아 +1 합니다.
4. 위 과정을 반복합니다.

[2023-09-11] wooyeol #205

---

Programmers/단어 변환/dohyun.py

풀이시간
- 약 1시간 30분
접근법
- 하나의 단어는 접근하면 다시 사용하지 않음 (왜? 다시 접근할거면 변환을 할 필요가 없으니까, 무한 루프도는거)
- 한번 방문한 곳은 다시 안감 + 완전탐색 + 최소 count -> BFS
- "한 번에 한 개의 알파벳만 바꿀 수 있다" 조건만 잘 처리하자!
- 단어의 길이가 최대 10이므로 그냥 단순 순회하며 확인해보면 될 듯함
회고
- 한 개의 알파벳만 바꿀 수 있다 -> "BCB" 와 같은 단어가 오면 "ACA" 로도 바꿀 수 있다
- 이렇게 해석을 잘 못해서 시간이 좀 오래 걸렸음 ㅠ ㅠ
- #184

[2023-09-08] dohyun #184

---

BOJ/연속합/jisu.py

풀이 시작 : 2023-09-10 16:19
- 제한 사항
- 수는 100,000개까지 주어지므로 O(NlogN) 알고리즘을 설계해야 한다.
- 풀이 방법
- 별도의 dp배열을 활용해 해당 배열의 i번째 원소는 수열에서 i번째부터 연속 합을 구했을 때의 가장 큰 합을 저장한다.
- 이를 위해 dp 배열을 순회하며 i-1번째 까지의 최대 연속합에 i번째 원소를 더할 것인지, i번쨰 원소부터 다시 시작할 지 결정해야 한다.
- 둘 중 최대값을 선택해 업데이트 한다. (`dp[i] = max(dp[i-1]+nums[i], nums[i])`)
- 주의 사항
- dp[i]반쩨 깂은 연속 합을 위해서 dp[i-1]에 좋든 싫든 수열의 i번째 원소를 고려한 값으로, dp배열의 마지막 값이 문제의 해는 아니다.
- 즉, dp배열의 최대값이 문제의 해이다.
풀이 완료 : 2023-09-10 16:50 (풀이 시간 : 31분)

[2023-09-11] jisu #204

---

BOJ/강의실 배정/dohyun.py

풀이시간
- 1시간 풀이 후 실패로 답지 참조
접근법
- N <= 이십만 -> 최대 O(NlogN) 복잡도로 해결
- 최대한 겹치는 시간이 없게 해야 최소의 강의실을 사용
- 틀린 풀이
- K 시간동안 강의실이 몇개 있는지를 딕셔너리에 담아보자
- 메모리초과..?
- 정답 풀이
- 정렬을 활용해서 수업의 시작과 끝을 체크하여 정답값을 갱신하는 형태
- 시작하면 +1, 종료하면 -1, 정답값은 가장 많이 수업이 진행되고 있을 때 강의실 수
회고
- 그동안 공간복잡도문제(메모리초과)가 있었던 적이 없어서 당황 ...
- 종료시간 범위가 10^9 이라 리스트가 아닌 딕셔너리를 활용해 더욱 메모리를 아꼈다고 생각했는데 턱없이 부족했던 것 같음
- 이런 유형(?)의 문제를 가끔 풀어봤던 것 같은데 항상 많이 취약했던 것 같음, 연습 하기!
- #207

[2023-09-13] dohyun #207

---

BOJ/잃어버린 괄호/jisu.py

풀이 시작 : 2023-09-11 14:20
- 주어지는 식의 길이는 최대 50
- 연산자는 '+' 아니면 '-'
- 맨 앞에 -가 오는 경우는 없으므로 여는 괄호는 연산자 뒤, 닫는 괄호는 다음 연산자 앞에 올 수 있음
- 최소 값을 만들기 위해 '-' 다음에 오는 구간을 최대로 만들어줘야 함
- '-'연산자 뒤에 괄호를 열고 다음 '-'가 나오기 전에 괄호를 닫으면 '-' 구간을 최대로 묶을 수 있음
- 55-50+40-10+20+30+40 -> 55-(50+40)-(10+20+30+40)
풀이 완료 : 2023-09-11 14:58 (풀이 시간 : 38분)

[2023-09-13] jisu #206

---

BOJ/강의실 배정/jisu.py

풀이 시작 : 2023-09-13 13:44
- N <= 200,000 이므로, O(NlogN) 알고리즘을 설계해야 한다.
- 일단 강의 시작 순서대로 주어진다는 조건이 없으므로 정렬 O(NlogN)
- 모든 배치된 강의실 중 가장 빨리 끝나는 강의실보다 현재 진행되어야 하는 강의가 더 빠르면 강의실을 추가해야 함
- 강의가 끝나는 시간을 담은 heap으로 강의실 배정 리스트를 관리한다.
- 모든 강의를 순회하며 해당 강의의 시작하는 시간이 가장 빨리 끝나는 강의실(heap의 root)의 끝나는 시간보다 더 빠른지 체크
- 더 빠르다면 힙에 해당 강의의 끝나는 시간 삽입 : 강의실을 추가한다는 의미
- 가장 빨리 끝나는 강의실의 강의가 더 빨리 끝난다면 heappop 후, 삽입 : 해당 강의실에 강의를 교체한다는 의미
- 순회 : O(N), heappush: O(logN) -> O(NlogN)
- 최종적으로 O(2NlogN)으로 풀이 가능
풀이 완료 : 2023-09-13 14:50 (1시간 6분 소요)

[2023-09-13] jisu #207

---

BOJ/골드바흐의 추측/wooyeol.py

골드바흐의 추측
풀이시간
20:44 ~ 21:28 (44분)
문제 조건
4 <= N <= 10,000
2 <= target <= 10,000인 짝수
시간 복잡도 :
O(값 입력 + 에라토스테네스의 체 만들기 + 골드바흐의 파티션 찾기)
접근법
무슨 알고리즘으로 풀이 할 수 있을까? -> 구현
1. 입력 받은 케이스 중 최대 값까지의 소수를 구하기 - 에라토스테네스의 체
2. 골드바흐 파티션 찾기 -> 두 소수의 차이가 가장 작은 것을 출력
- 가장 작은 소수 값부터 확인하며 
- 작은 소수 값이 먼저 나오며 target 값에서 작은 소수 값을 제외한 값이 소수일 경우 중
- 두 소수의 차이가 최소일 경우 정답에 두 소수의 값 업데이트

[2023-09-15] wooyeol #208

---

BOJ/골드바흐의 추측/sumin.py

**풀이 시간**: 22분
**\<input>**
t: 테스트케이스
n: 찾아야 하는 골드바흐 파티션의 합이 되는 짝수(4 ≤ n ≤ 10,000)
합이 n이 되는 짝수를 어떻게 찾을 수 있을까?
- 2 ~ 최대 10,000개까지의 소수 중 합이 n이 되게 하는 두 소수를 찾기 위해서 투포인터를 사용할 수 있다.
- 소수가 정렬돼있는 상태이기 때문에 left는 시작 인덱스, right은 끝 인덱스로 초기화 후, 두 소수의 합을 계속해서 target과 비교하며 포인터를 이동시킨다.
**<시간복잡도>**
`O(nlog(logn))`: 에라토스테네스의체
find_parition 함수는 최대 O(n)
뭔가 더 최적화할 수 있는 방법이 있을 것 같은데 생각이 안남.... 여러분의 신박한 풀이 기다립니다..

[2023-09-15] sumin #208

---

BOJ/골드바흐의 추측/dohyun.py

풀이시간
- 약 30분
접근법
- n <= 10000 -> O(NlogN)
- 에라토스테네스의 체? 아직 암기 못함 -> 업그레이드 버전 소수 판별로 가자..!
- 작은 수의 소수를 left 라고했을 떄 number - left 가 소수이면 OK
- 여러가지 경우가 나올걸 대비해 차이를 갱신
- n 이 1만까지이므로 미리 소수를 구해놓고, set 자료형을 활용하여 시간복잡도 개선
회고
- n 이 매우 컸다면 메모리초과 문제가 발생했을 것 같은 생각
- 근데 에라토스테네스의 체도 마찬가지일 것 같음 (그냥 n이 매우 크게 주어지지가 않을듯!)
- #208

[2023-09-15] dohyun #208

---

Programmers/모음사전/jisu.py

풀이 시작 : 2023-09-17 15:38
- 모든 단어는 길이 5이하이다.
A : 1부터 시작
E : 782
I : 1563
AA : 2
AE : 158
AAA : 3
AAE : 34
AAAA : 4
AAAE : 10 
AAAAA : 5
AAAAE : 6
- 모음 사전을 DFS로 생성 후, index 메서드로 단어 길이 별 A와 E의 길이를 얻기
- 첫 번째 자리의 알파벳 하나 차이 : 781
- 두 번째 자리의 알파벳 하나 차이 : 156
- 세 번째 자리의 알파벳 하나 차이 : 31
- 네 번째 자리의 알파벳 하나 차이 : 6
- 다섯 번째 자리의 알파벳 하나 차이 : 1
- A와 E의 차이를 통해 알파벳 길이 별 모음 하나만큼의 개수를 알 수 있음
- 미리 구해놓은 차이만큼 알파벳을 계산해서 최종 모음사전 순서 얻기
- 단어 순서는 1부터 시작함에 유의해야 한다. (T+1)의 악몽...
풀이 완료 : 2023-09-17 16:11 (풀이 시간 : 33분)

[2023-09-18] jisu #237

---

Programmers/방문 길이/wooyeol.py

방문 길이
https://school.programmers.co.kr/learn/courses/30/lessons/49994
풀이시간 
10:50 ~ 11:33 (43분)
문제 조건
1 <= len(dirs) : D <= 500
시간 복잡도 : 
O(D * (D + D)) = O(D^2)
접근법
무슨 알고리즘으로 풀이 할 수 있을까? -> 시뮬레이션(해쉬 테이블)
- 방문했던 장소를 기억해야하는 해쉬 테이블 설계
1. 좌표를 업데이트하는데 범위 밖으로 넘어가서 이동하지 않으면 거리 체크 X
2. 이동한 좌표와 이동하기 전 좌표의 이동한 길을 방문한적 있는지 확인 후 없으면 중복이 제거된 이동한 거리 증가
- 무방향성으로 길을 체크해야하기 때문에 (이동 전 좌표에서 이동 후 좌표)와 (이동 후 좌표에서 이동 전 좌표) 모두 체크

[2023-09-22] wooyeol #240

---

Programmers/뒤에 있는 큰 수 찾기/wooyeol.py

뒤에 있는 큰 수 찾기
https://school.programmers.co.kr/learn/courses/30/lessons/154539
풀이시간 
11 :42~48 13:38 ~ 14:10 (풀이 포기)
풀이 참고 : https://maximum-curry30.tistory.com/515
문제 조건
4 <= len(numbers) : N <= 1,000,000
시간 복잡도 : 
O(N)
접근법
무슨 알고리즘으로 풀이 할 수 있을까? -> stack
- 오큰수 처리 알고리즘이 존재
- Stack을 사용하여 가장 위의 원소에 해당하는 값보다 현재 검사하는 원소의 값이 작을 때 해당 수가 오 큰수이다.

[2023-09-22] wooyeol #241

---

BOJ/공유기 설치/sumin.py

**풀이시간**: 25분
**\<input>**
n: 집의 개수(2 ≤ N ≤ 200,000)
c: 공유기의 개수(2 ≤ C ≤ N)
집의 좌표 xi (0 ≤ xi ≤ 1,000,000,000)가 주어짐
1. 가장 인접한 두 공유기 사이의 거리를 이분탐색한다.
2. 가장 인접한 집 간의 거리를 유지하면서 최대한 많은 공유기를 설치했을 때, C개 이상 설치할 수 있으면 정답의 후보가 된다.
- 가능한 경우면, 거리를 더 크게 -> 더 적은 공유기 설치 가능
- 불가능한 경우면, 거리를 더 작게 -> 더 많은 공유기 설치 가능
**\<시간복잡도>**
O(nlogn)

[2023-09-25] sumin #266

---

BOJ/List of Unique Numbers/jisu.py

풀이 시작 : 2023-09-27 10:28
N <= 100,000 이므로 O(NlogN) 이하의 알고리즘을 설계해야 한다.
- 투 포인터로 접근 (`low, high = 0, 0`)
- high 인덱스의 값이 현재 sub_set 집합에 없으면 
- sub_set 집합에 high 인덱스의 값을 add
- 이후 high를 넓혀서 탐색
- 경우의 수 1 증가
- 집합에 이미 있는 경우 같은 수가 하나의 경우에 여러번 나타난 것
- sub_set을 초기화 하고 low, high를 low+1로 초기화
풀이 중단 : 2023-09-27 11:00 (32분 경과)
- low번째 인덱스부터 중복 없는 high인덱스까지의 경우의 수는 그 구간의 길이임
- 예를 들어 1 2 3 1 2 에서 중복 없는 1 2 3 구간에서 1부터 시작하는 경우의 수는 1, 12, 123 => 3가지이므로 구간의 길이
- 따라서 low로 순회하면서, high를 low와 중복되지 않는 인덱스까지 넓히며 탐색을 반복하면 된다.
- 1 2 3 -> 2 3 1 -> 3 1 2 -> 1 2 -> 2 : 12개의 경우의 수
메모리 | 시간
-- | --
44844KB | 152ms

[2023-09-27] jisu #269

---

BOJ/싸이버개강총회/sumin.py

**풀이시간**: 20분
**\<input>**
- s: 개강총회 시작 시간
- e: 개강총회를 끝낸 시간
- q: 스트리밍을 끝낸 시간
(00:00 ≤ S < E < Q ≤ 23:59)
최대 10만개의 채팅 기록이 주어진다.
문제에 주어진대로 구현
1) 개강총회를 시작하기 전, 입장 확인
2) 개강총회를 끝내고 나서 스트리밍을 끝날 때, 퇴장 확인
두 경우를 set자료형을 통해 확인한다.
채팅 기록이 시간 순서대로 주어지기 때문에 입장 확인이 됐다면 set에 추가하고, 입장확인된 학회원이 제대로 퇴장했다면 해당 이름을 제거한다.
**<시간복잡도>**
`O(채팅 기록의 수)`: 최대 10만

[2023-09-29] sumin #270

---

BOJ/싸이버개강총회/jisu.py

풀이 시작 : 2023-09-28 16:20
- 스트리밍 시작 -> 개강총회 시작 -> 개강총회 끝 -> 스트리밍 끝
- 스트리밍 시작 -> 개총(S) : 개강총회 시작 정시까지 채팅 기록 체크
- 개강총회 끝(E) -> 스트리밍 끝(Q) : 채팅 기록 체크
- 시간에 대한 문자열을 모두 datetime.datetime.strptime() 으로 파싱
- 시간에 대한 대소 비교를 수행하며
- 개총 이전 시간의 기록 : set에다가 이름 기록
- 개총 ~ 개총끝 : 패스
- 개총끝 ~ 스트리밍 끝 : 기록된 이름이 있는 경우 카운트
- 이때 중복해서 채팅 치는 경우를 고려해 또 다른 set에다 넣어서 개수를 센다.
- 시간에 대한 대소 비교 수행 시 부등호(이상, 초과) 조심해야 함!
풀이 완료 : 2023-09-28 17:10 (풀이 시간 : 50분 소요)
메모리 | 시간
-- | --
59568KB | 824ms

[2023-09-29] jisu #270

---

BOJ/싸이버개강총회/wooyeol.py

싸이버개강총회
https://www.acmicpc.net/problem/19583
풀이시간 
11:20 ~ 12:10 (50분)
문제 조건
(00:00 ≤ S < E < Q ≤ 23:59)
0 < 채팅 기록 < 10만
시간 복잡도 :
strptime은 N 길이의 문자열의 길이를 파싱할 때 O(N) - O(5)
O(100,000)
접근법
무슨 알고리즘으로 풀이 할 수 있을까? -> 해시 테이블
시간을 datetime 객체로 변환 후 조건의 시간들과 비교하여 
출석부에 삽입 혹은 제거 연산을 시행하고 그 횟수를 남긴다.

[2023-09-29] wooyeol #270

---

Programmers/주식가격/jisu.py

풀이 시작 : 2023-10-01 13:54
- prices의 길이는 100,000 이하이므로 O(NlogN) 이하의 알고리즘을 설계해야 한다.
- i번째 요소부터 모든 원소를 비교하는 방법으로 하면 시간 초과가 날 것
풀이 중단 : 2023-10-01 14:54 (1시간 경과)
- 스택을 활용, 스택에 떨어지지 않는 부분까지의 인댁스를 담고, 증가하지 않는 부분의 인덱스의 차를 활용한다.
- [1, 2, 3, 2, 3]의 경우 0번째부터 떨어지지 않는 부분까지 스택에 push -> stack : [0, 1, 2]
- `idx(3)`번째의 2는 `stack[-1](2)`번째 원소보다 작으므로, `idx-stack[-1]` = 3 - 2 = 1초 동안 떨어지지 않음
- 다음 떨어지지 않는 부분까지인 3번째 4번째 인덱스까지 스택에 담으면 최종적으로 [0, 1, 3, 4]
- 스택에 남아있는 값들은 끝날 때까지 가격이 떨어지지 않은 것이다.
- 따라서 해당 idx의 떨어지지 않는 기간은 `len(prices)-1` 초에서 해당 `idx`를 뺀 기간이다.
풀이 완료 : 2023-10-01 15:25 (1시간 31분 소요)

[2023-10-02] jisu #296

---

Softeer/순서대로 방문하기/sumin.py

**풀이시간**: 40분
**\<input>**
n: 격자의 크기(2 ≤ n ≤ 4)
m: 순서대로 방문해야 하는 칸의 수(2 ≤ m ≤ n^2)
n개의 수(0 or 1)
- 0: 빈 칸
- 1: 벽
방문해야할 m개의 칸 (x, y)가 주어진다
- 주어진 칸에 벽이 있는 경우능 없고, 중복도 없다.
n과 m이 매우 작기 때문에 DFS를 통해 모든 경우의 수를 확인한다.(브루트 포스)
이 때, 더 이상 다음 칸으로 이동할 수 없다면 탐색을 포기한다.(백트래킹)
<시간복잡도>
`O(N^2)`

[2023-10-09] sumin #313

---

Programmers/프렌즈4블록/jisu.py

풀이 시작 : 2023-10-06 13:05
- mxn은 최대 30x30
- 구현에 집중
- 시뮬레이션
- 한번 전체 탐색으로 없어질 블록 탐색
- 카운트 후 없애야 함(겹치는 부분도 없어져야 하므로)
- 없어진 좌표 기준으로 블록 '한 칸' 내리기
- 겹치는 블럭을 고려하기 위해 없애아 하는 좌표는 set으로 관리한다.
- 주의!
- 없어진 블록을 채울 때 아래 블록 한 칸을 먼저 채우게 되면 바로 위 없어져야할 블록이 아래 블록으로 채워지게 되므로 오류
- 정렬을 통해 없어질 블록 중 위 블록을 먼저 채워야 한다.
- 정렬을 위해 불가피하게 리스트로 변환 후 정렬을 수행한다.
풀이 완료 : 2023-10-06 13:28(풀이시간 : 23분 소요)
- 정확성 테스트
테스트 1 〉 | 통과 (0.03ms, 10.6MB)
-- | --
테스트 2 〉 | 통과 (0.04ms, 10.4MB)
테스트 3 〉 | 통과 (0.01ms, 10.6MB)
테스트 4 〉 | 통과 (2.88ms, 10.7MB)
테스트 5 〉 | 통과 (29.51ms, 10.6MB)
테스트 6 〉 | 통과 (4.77ms, 10.5MB)
테스트 7 〉 | 통과 (1.44ms, 10.6MB)
테스트 8 〉 | 통과 (3.01ms, 10.7MB)
테스트 9 〉 | 통과 (0.03ms, 10.5MB)
테스트 10 〉 | 통과 (0.74ms, 10.6MB)
테스트 11 〉 | 통과 (2.82ms, 10.6MB)
</pre>

[2023-10-06] jisu #300

---

Softeer/순서대로 방문하기/jisu.py

풀이 시작 : 2023-10-08 14:41
- 2 <= n <= 4
- 2 <= m <= 16
- 방문 지점의 방문 순서를 matrix에 기록
- '0' : 빈 칸 / '1' : 벽 / 0 ~ m : 방문 지점
- 스킬트리 문제처럼, 특정 방문 지점에 방문하기 위해서는 직전 지점이 방문되어야 함
- 다음 지점이 방문 지점인 경우, 직전 지점이 방문된 경우에만 탐색하도록 dfs
- 마지막 방문 순서에 해당하는 지점을 탐색하면 경우의 수 +1 후 dfs 종료
풀이 완료 : 2023-10-08 15:19 (풀이 시간 : 38분)

[2023-10-08] jisu #313

---

Programmers/스킬트리/wooyeol.py

스킬트리
https://school.programmers.co.kr/learn/courses/30/lessons/49993
풀이시간 
10:23 ~ 10:39 (16분)
문제 조건
1 <= len(skill) <= 26
1 <= len(skill_trees) <= 20
2 <= 각 skill_trees의 길이 <= 26
시간 복잡도 : 
O(20 * 26)
접근법
무슨 알고리즘으로 풀이 할 수 있을까? -> 완전 탐색
데이터의 중복과 갯수가 크게 문제 되지 않기 때문에 완전 탐색으로 단순 구현을 진행하였습니다.
완전 탐색 과정
각각의 스킬트리 과정을 확인합니다.
- 선행 스킬의 인덱스를 증가시키며 선행 스킬이 순서대로 주어지는지 확인하기
- 스킬트리의 스킬을 하나씩 확인하고 선행 스킬에 포함된다면 등장해야하는 선행 스킬과 비교
- 정상일 경우 다음 선행 스킬의 인덱스로 증가
- 아니라면 인터럽트
- 인터럽트가 일어나지 않은 스킬트리는 정답으로 인정

[2023-10-02] wooyeol #297

---

Programmers/파일명 정렬/sumin.py

**풀이시간**: 20분
**\<input>**
files: 파일명(100글자 이내, 영문 대소문자, 숫자, 공백, 마침표, 빼기 부호만으로 이루어져있음), 1000개 이하의 파일
- 영문자로 시작하며, 숫자를 하나 이상 포함
- HEAD: 최소 한 글자 이상의 문자
- NUMBER: 한 글자에서 최대 다섯글자 사이의 연속된 숫자(앞쪽에 0이 올 수 있음. 0~9999 사이의 숫자)
- TAIL: 숫자가 다시 나타날 수도, 아무 글자도 없을 수도 있다.
head, number, tail을 나눠주고 정렬
**<시간복잡도>**
`O(1000 * 100)`: files의 크기 * file의 최대 길이
**<회고>**
head, number, tail을 일일히 나눠서 구현했는데..
다른 사람들 풀이를 보니 정규표현식으로 아주 깔끔하게 구현한 걸 확인..
[정규표현식 풀이]
정규표현식으로 구현할 때, number를 먼저 정렬하고, head를 정렬한다. 순서가 바뀌는 점 주의!
또, 파이썬 정렬에서 ['123', '0123']의 각 원소를 int로 변환해 정렬한다 했을 때, 같은 값이라면 순서도 유지된다는 걸 처음 알았음..

[2023-10-04] sumin #299

---

Programmers/프렌즈4블록/sumin.py

**풀이시간**: 35분
**\<input>**
m: 판의 높이(2 ≦ n, m ≦ 30)
n: 판의 폭(2 ≦ n, m ≦ 30)
board: 판의 배치 정보(대문자 A-Z)
문제에서 주어진대로 구현한다.
더 이상 제거되는 블록이 없을 때까지 다음의 과정을 반복
1. 제거되는 블록 확인하기(2x2)
- 제거되는 블록의 좌상단 좌표만 따로 보관하기
2. 제거되는 블록은 .으로 값 변경하기
- 제거되는 블록의 좌상단 좌표를 이용해 2x2 칸은 모두 .으로 변경
3. 제거되는 블록의 위 블록들 내려주기
- 재귀를 통해 더 이상 블록을 내릴 수 없을 때까지 제거된 블록 위의 블록들 내려주기
**\<시간복잡도>**
O(NM) + O(NM) + O(NM) = O(3NM) = `O(NM)`을 더 이상 블록이 제거될 수 없을 때까지 반복
- 제거되는 블록이 있는지 확인
- 제거되는 블록 .으로 변경
- 블록을 내리는 작업

[2023-10-06] sumin #300

---

Programmers/롤케이크 자르기/sumin.py

**풀이시간**: 20분
**\<input>**
topping: 롤케이크에 올려진 토핑들의 번호를 저장한 정수배열(1 ≤ topping의 길이 ≤ 1,000,000)
- 1 ≤ topping의 원소 ≤ 10,000
전체 토핑의 개수와 토핑의 가짓수에서 철수가 먹게되는 토핑의 개수와 가짓수를 계속해서 갱신하며 답을 찾아나간다.
이 때, set 자료형을 써서 철수가 먹게되는 토핑의 가짓수를 O(1)에 탐색한다.
**<시간복잡도>**
`O(N)`

[2023-10-06] sumin #301

---

BOJ/2048 (Easy)/jisu.py

풀이 시작 : 2023-10-11 16:00
- 보드 크기 1 1 <= N <= 20
- 보드 내부 수 < 1024
- 시뮬레이션
- 최대 5번 이동시키는 경우의 수는 5 ** 4 = 625
- 한 번의 재귀에서 N^2이어도 20 * 40 = 400
- 625 * 400 = 250000의 연산량이므로 N^2이 훨씬 넘어도 괜찮다.
- 한 번 합쳐진 블록은 또 합쳐질 수 없음 => 별도의 표시 필요
- up, down, left, right를 구현해야 함
- 각 이동 메서드는 어떻게 구현?
- 1. 0이 아닌 비교하여 합칠 값 찾기
- 2. 판단 후 합치기
- 2-1. 값이 같고 아직 합쳐지지 않은 경우 합치기
- 2-2. 바꿀 위치가 0인 경우
- 2-3. 그 외 합칠 수 없는 경우 끌어 올리기만
- trick
- up-left 는 row와 col을 바꿔서 그대로 로직을 적용하면 됨
- down-right 는 up-left에서 배열을 반전시켜 적용 후 다시 반전시켜주면 됨
- 각 상태공간에서 matrix는 독립적이므로 깊은 복사(deepcopy) 필요
풀이 중단 : 2023-10-11 17:10 (1시간 10분 경과)
풀이 재개 : 2023-10-12 13:10
풀이 완료 : 2023-10-12 14:10 (2시간 10분 소요)

[2023-10-13] jisu #332

---

CodeTree/메이즈 러너/wooyeol.py

메이즈 러너
https://www.codetree.ai/training-field/frequent-problems/problems/maze-runner/description?page=1&pageSize=20
풀이시간 
10:20 ~ 11 :54
13:12 ~ 14: 04
14:14 ~ 18:09 (6시간 19분)
문제 조건
N: 미로의 크기 (4≤N≤10)
M: 참가자 수 (1≤M≤10)
K: 게임 시간 (1≤K≤100)
시간 복잡도 : 
O(K * (M^2 + M + MlogM + N^2 + M + N^2))
O(100 * (100 + 10 + 10log10 + 100 + 10 + 100))
접근법
무슨 알고리즘으로 풀이 할 수 있을까? -> 시뮬레이션
1초 동안 진행하기 위해 필요한 연산들
- 현재 턴에 모든 플레이어 이동
- 1초마다 상하좌우를 검사하고 최단 거리가 갱신되는 칸으로 이동
- 가장 작은 정사각형 확인하기
- 모든 플레이어를 기준으로 좌상단에 가까운 가장 작은 사각형을 만들고 그 중에서 가장 작은 정사각형 반환
- 가장 작은 정사각형 회전하기
- 임시 정사각형을 만들어서 회전시킨 값을 저장시키고 회전된 값을 다시 미로에 적용

[2023-10-13] wooyeol #335

---

CodeTree/메이즈 러너/jisu.py

풀이 시작 : 2023-10-13 12:40 (이후 시간을 측정하지 않고 과제 느낌으로 풀이)
- 미로의 크기 : 4 <= N <= 10
- 참가자 수 : 1 <= M <= 10
- 게임 시간 : 1 <= K <= 100
1. 이동
2. 회전
2-1. 정사각형 찾기
2-2. 회전시키기
풀이 완료 : 2023-10-14 18:03 (이틀동안 이거만 함 ㅎㅎ..)
수행시간 | 메모리
--|--
327ms | 27MB

[2023-10-13] jisu #335
