RecoRecoNi/Algorithm-Study

Programmers - 문제풀이/택배 배달과 수거하기/wooyeol.py

택배 배달과 수거하기 풀이
무슨 알고리즘으로 풀이 할 수 있을까? -> 그리디
- 두 리스트가 주어지고 cap 만큼 택배 상자를 제거해나가야한다.
- 하나는 전달하면 사라지고 하나는 회수해야 사라진다.
최소 경로 동선은 가장 먼 집부터 문제를 해결하였을 때 구할 수 있다.
현재까지의 주소지에 택배 전달 + 가능한 수거 모두 하기
- #1

Create 택배 배달과 수거하기 wooyeol.py

---

Programmers - 문제풀이/택배 배달과 수거하기/dohyun.py

접근법
- 최단거리를 구해야하기 대문에 물류창고에서 출발할 때 최대한 멀리가는 것이 좋을 것 같다고 생각 -> 그리디 알고리즘
- 어차피 멀리있는 집도 배달하러 가야하므로 돌아오는 길에 수거하기 편리
- 즉 멀리 있는 집을 최대한 먼저 배달하고, 돌아올 때도 멀리있는 집 순으로 수거를 빨리 해야함 
- 모든 집을 들린다고 코드를 설계한 후 실제로 배달 또는 수거가 있었을 경우에 가장 먼 거리를 answer 에 더하는게 낫겠다!
회고
- 2시간 가까이 풀었는데 테스트 케이스에서 안 맞아서 레퍼런스 확인 ㅜㅜ
- 많은 레퍼런스 중 배열을 역순으로 정렬하는 것보다 반복문의 인덱스를 뒤에서부터 가는 것이 조금 더 직관적인 것 같아 해당 풀이로 선택
- 본인 풀이와 비슷한 풀이가 전혀 없었음, 아예 설계 자체를 잘 못한 것 같다는 생각
- 예시를 그대로 구현하기 보다는 어떻게 더 간단하게 설계할 수 있을까를 고민하는게 더 효율적인 것 같다
- 시간 복잡도를 미리 구상하고 코드를 설계하는 습관을 들여야 할 것 같음
- #1

Create 택배 배달과 수거하기 dohyun.py

---

sumin.py

전에 풀어봤던 문제였고, 처음 풀었을 때 풀이참조
이번에 다시 풀었을 때, 주석까지 세세하게 다는 데 1시간 정도 걸림
<input>
- cap: 최대 실을 수 있는 상자 개수(최대 50)
- n: 배달할 집의 개수(최대 10만) -> 최대 O(NlogN) 알고리즘으로 접근해야 함
- deliveries: 배달할 재활용 택배 상자의 개수(최대 50)
- pickups: 수거할 빈 재활용 택배 상자의 개수(최대 50)
<solution>
1. 가장 먼 집부터 방문하기
2. 배달과 수거를 분리해서 생각(트럭이 실을 수 있는 최대용량)
-> 시간복잡도: O(n)
- #1

Create 택배 배달과 수거하기 sumin.py

---

BOJ/에디터/yerim.py

접근 방법
- 처음에는, 문자열을 리스트로 변환해 pop, insert 연산 => 시간 초과가 계속 남 
- insert, remove 함수는 O(n)만큼의 시간을 소요하는데, 최대 명령 수가 매우 커서 시간 초과가 난다고 함 
- 따라서 [블로그](https://seongonion.tistory.com/53)를 참고해 커서를 기준으로 문자열을 두 곳에 나누어 담음
- pop, append 연산으로 시간 초과 해결 가능!
- 또한 sys를 이용해 문자열을 입력 받아야 시간 초과가 나지 않음
- #10

[2023-05-15] yerim #10

---

Programmers - 문제풀이/요격 시스템/jisu.py

> 핵심은 미사일 범위 끝을 기준으로 정렬해서 활용하는 것
- 첫 접근
- 첫 접근시에는 정렬 후 리스트를 뒤집어서 그림 상 뒤에서부터 접근해보았다.
- 특정 미사일의 끝 부분이 다음 미사일의 시작 부분보다 작다면 겹치는 것이기 때문에 카운트 하지 않고, 겹치지 않게 되었을 때 카운트 하는 방식
- 모든 예외를 고려할 수 없었고 로직이 복잡해졌다.
- 다시 접근
- 뒤에서부터 시작한 로직을 다시 앞에서부터 접근해보았다.
- 관점을 바꿔서 현재 바라보고 있는 미사일의 시작 부분이 이전 미사일의 끝 부분보다 작다면 겹쳐서 함께 터지니 패스
-  겹치지 않게 된다면 다음 미사일을 위해 한 발 더 쏴야하므로 카운트해주는 방식으로 해결하였다.
- REFERENCE
- [테스트 케이스 2개](https://school.programmers.co.kr/questions/47378)  
- #2

[2023-05-14] jisu #2

---

Baekjoon - 문제풀이/에디터/jisu.py

이전에 문제를 풀어봤던 경험이 있어서 바로 접근할 수 있었다.
자료구조 하나만을 활용한다면, 문자 사이에 삽입, 제거하는 연산의 복잡도가 각 O(N)이기 때문에 시간 초과가 발생할 것이다.
또, 경험상 굉장히 헷갈려서 머리아팠던 기억이 있다.. 
두 개의 deque을 활용해서 커서 기준 왼쪽, 오른쪽 문자열로 활용하자!
deque은 double linked list기반 자료구조이기 때문에 오른쪽 왼쪽 어느 곳에서 삽입, 삭제 연산을 진행하더라도 O(1)이다.
이를 통해 효율적이면서 직관적으로 문제를 해결할 수 있다.
문제의 메모리 제한을 잘 확인해서 하나의 자료구조에 얽매이지 않고 필요하다면 여러 자료구조를 동시에 활용하자!
- #10

[2023-05-15] jisu #10

---

BOJ/에디터/sumin.py

스택 두개를 활용해 문제 해결
링크드 리스트로 분류되는 문제이지만, 이 문제에서는 파이썬의 리스트(동적 배열)만으로도 링크드 리스트 문제를 해결할 수 있다. 코드 상 앞쪽에서 삭제가 발생하지 않기 때문에 시간복잡도 역시 연산은 모두 O(1)로 가능하다
시간복잡도: O(N)
- #10

[2023-05-15] sumin #10

---

BOJ/에디터/dohyun.py

풀이시간
- 약 30분 소요
접근법
- 리스트로 접근하는 것 보다는 문자열로 접근하는 것이 더 빠를 것이라고 생각했음
- 구현하는데에는 딱히 어려운 점은 없었음
- 하지만 시간초과 오류가 발생 (해당 문제가 시간제한이 조금 빡세다고 함)
- 시간초과 문제를 해결하지 못해서 결국 레퍼런스 참조
- append, pop 의 시간복잡도가 O(1) 인 것을 활용하여 스택 두 개를 사용하는 것이 핵심
회고
- 스택 자료구조에 대해서 조금 더 알아보자!
- #10

[2023-05-15] dohyun #10 

---

BOJ/키로거/dohyun.py

풀이시간
- 약 20분 소요
접근법
- 문자열의 길이가 생각보다 길다! 시간복잡도를 줄여야 할 듯
- 문제를 읽어보니 BOJ 에디터 문제의 접근과 거의 완전히 유사함
- 지수님의 deque 풀이에 영감을 받아 참고해서 풀이 ㅎㅎ..
회고
- 이전 문제를 잘 이해하고 넘어가면 비슷한 유형을 만났을 때 빠르게 풀이가 가능하다! 문제 대충 넘어가지말고 잘 이해하자
- 이 문제는 왜인지는 모르겠지만 sys.stdin.readline() 을 사용할 때 보다 input() 을 사용한게 더 빨랐다..?
- #11

[2023-05-18] dohyun #11

---

Programmers - 문제풀이/이모티콘 할인행사/dohyun.py

**풀이시간**
- 약 2시간 가량 풀다가 계속 테스트케이스가 안 맞아서 [레퍼런스](https://blogeon.tistory.com/entry/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4-LV2-%ED%8C%8C%EC%9D%B4%EC%8D%AC-Python-%EC%9D%B4%EB%AA%A8%ED%8B%B0%EC%BD%98-%ED%95%A0%EC%9D%B8%ED%96%89%EC%82%AC) 참조
**접근법**
- user 와 emoticon 의 길이가 그렇게 길지 않다 -> 시간 복잡도는 크게 생각안해도 될 것 같음
- 개별 아이템에 할인 비율을 막 조절하는 방법은 너무 복잡함 -> 구현 느낌 보다는 키 포인트가 되는 아이디어를 떠올려야 할 듯
- 라고 생각하고 오래동안 삽질하다가 말이 안된다고 느껴서 문제를 다시 읽어보니 할인율은 10, 20, 30, 40 중 하나였다 ㅠㅠ
- 시간복잡도도 크게 고려하지 않아도 되니 노가다(?)를 하면 되겠다 라고 생각
**회고**
- 구현 문제를 조금 더 연습해봐야겠다는 것을 느낌, 사실 접근이 어려운 문제가 아니었는데 구현 능력이 부족해서 못 푼다는 건 많이 아쉽다!
- itertools 의 product 를 몇 번 써본적이 있었는데도 생각해내지 못했음, 반성하자 ..!
- #26

[2023-05-21] dohyun #26

---

Programmers - 문제풀이/두 원 사이의 정수 쌍/jisu.py

- 첫 번째 접근 : 완전탐색 (시간 초과)
- 두 번째 접근 
- 1사분면 기준 축(axis) 위 점들 제외, 원 사이의 공간에 있는 점들의 개수를 구하기
- 원 내부 공간의 점 개수를 구하는 get_num_of_points_in_circle 활용
- get_num_of_points_in_circle(r2) - get_num_of_points_in_circle(r1) 하면 두 원 사이 공간의 점들의 개수를 구할 있다.
- 하지만 예외를 고려해야하는디...
- 두 번째 원 내부 점의 개수를 첫 번째 원 내부 점 개수에서 뺄 때 두 번째 원 위의 점까지 같이 빼지는 이슈
- flog 인자를 두어서 두 번째 원 내부 점 개수를 구할 때만 예외처리
- 1사분면 기준으로 원 사이 공간 점들의 개수를 구했으므로 * 4를 해주어 전체 원 사이 공간 점의 개수를 얻는다.
- 축 위의 점들을 제외했으므로 축 위의 점들을 추가로 고려해주기
- num_of_points_on_axis
- #27

[2023-05-30] jisu #27

---

BOJ/키로거/wooyeol.py

키로거
https://www.acmicpc.net/problem/5397
접근법
무슨 알고리즘으로 풀이 할 수 있을까? -> deque을 사용해서 cursur를 기준으로 데이터 이동
1. 커서 문제가 나오면 연결리스트 방식과 다음과 같이 
cursur를 기준으로 공간을 생각하여 풀이하는 방식으로 풀이 할 수 잇을 것 같았다.
결국 풀이는 두개의 덱을 사용한 이전 에디터 문제와 동일한 형식을 사용하여 풀이 할 수 있었다.
- #11

[2023-05-22] wooyeol #11

---

Programmers - 문제풀이/두 원 사이의 정수 쌍/wooyeol.py

두 원 사이의 정수 쌍
https://school.programmers.co.kr/learn/courses/30/lessons/181187
접근법
무슨 알고리즘으로 풀이 할 수 있을까? -> 단순 구현
1. r2에 포함되는 정수 좌표 - r1에 포함되는 정수 좌표
(r2 원의 내접사각형 + r2의 x축과 y축에 접하는 점 4개) - (r1 원의 내접 사각형)
`5**2 - 3**2 + 4`
`(r2지름 - 1)^2 - (r1지름 - 1)^2 + 4`
- r1 < r2
- r1 >= 1
2. 피타고라스를 사용하여 직접 구해보자
풀이참조 : https://school.programmers.co.kr/questions/47373
`x^2 + y^2 = r^2`
`r^2 - x^2 = y^2`
`y = sqrt(r^2 - x^2)`
- #27

[2023-05-30] wooyeol #27

---

BOJ/에디터/yerim.py
Programmers - 문제풀이/두 원 사이의 정수 쌍/yerim.py

풀이 시간 : 1시간
시간 초과가 계속 떠서 답안 확인
[접근 방법]
- 큰 원 안의 점 개수 - 작은 원 안의 점 개수
- 사분면에서 다 대칭이므로 한 면에서만 구하고 4를 곱해주면 됨
- 원의 반지름과 거리를 바탕으로 높이 계산
- 작은 원의 높이가 0이면 +1을 해주기 위해 반올림 후 +1 하는 방식 사용
[참고한 블로그](https://safetymo.tistory.com/13)
- #27

[2023-05-30] yerim #27

---

BOJ/제로/yerim.py

- 백준 10773번: 제로 (Silver 4)
- https://www.acmicpc.net/problem/10773
- 소요 시간 : 10분
- #40

[2023-06-01] yerim #40

---

BOJ/제로/sumin.py

**<풀이 시간>**
3분
**\<input\>**
k : 1 ≤ K ≤ 100,000
**\<solution\>**
전형적인 stack 문제
1) 0이 입력되면, stack의 top을 제거
2) 0이 아닌 경우, 해당 수를 stack에 추가
3) 적어낸 수의 합을 sum(stack)으로 구할 수 있지만, 또 O(k)의 연산을 할 필요없이 입력값이 들어왔을 때 바로바로 갱신해주기
-> 사소한 부분이지만 위 방식의 경우 84ms가 걸리고, sum(stack)의 경우 112ms가 걸렸음
- #40

[2023-05-31] sumin #40

---

BOJ/제로/dohyun.py

풀이시간
- 약 4분
접근법
- 제한시간 1초 + 입력 K 가 최대 10만번이기 때문에 시간 복잡도 보다는 빠르게 구현하는걸 연습해보자
- 익숙해지도록 deque 를 활용해서 풀이해보려고 했음, 근데 왜이렇게 쉽지??? 이게맞나??? 하면서 풀이
회고
- 몬가 참신한 다른 풀이가 보고싶다!
- #40

[2023-06-01] dohyun #40

---

BOJ/제로/wooyeol.py

단순 스택에 대한 문제로 list의 pop, append 연산으로 구현이 가능하다.
- #40

[2023-05-31] wooyeol #40

---

Programmers - 문제풀이/표현 가능한 이진트리/yerim.py

[프로그래머스 - 표현 가능한 이진트리](https://school.programmers.co.kr/learn/courses/30/lessons/150367)
- 15분 정도 문제 이해에만 힘을 쏟았는데 이해가 안돼서 [정답](https://ddingmin00.tistory.com/entry/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4-%ED%8C%8C%EC%9D%B4%EC%8D%AC-2023-KAKAO-BLIND-RECRUITMENT-%ED%91%9C%ED%98%84-%EA%B0%80%EB%8A%A5%ED%95%9C-%EC%9D%B4%EC%A7%84%ED%8A%B8%EB%A6%AC) 참고
- 문제 이해부터 풀이까지 다 너무 어려웠음.
- #47

[2023-06-08] yerim #47

---

BOJ/스택 수열/sumin.py

풀이시간: 30분
**\<input\>**
n : 1 ≤ n ≤ 100,000
-> 최대 O(nlogn)으로 설계 가능
**\<solution\>**
1. 주어진 수열의 수를 순서대로 하나씩 확인한다.
2. 확인하고 있는 수와 지금까지 스택에 넣은 가장 큰 수를 비교한다.
2-1. 확인하고 있는 수가 현재까지 스택에 넣은 가장 큰 수보다 큰 경우
- 수열에 '지금까지 넣은 가장 큰 수+1'부터 '현재 확인하고 있는 수'까지 스택에 push한다. ans에 +를 추가한다.
- 스택의 top(현재 확인하고 있는 수와 동일)을 pop하고, ans에 -를 추가한다.
2-2. 확인하고 있는 수가 현재까지 스택에 넣은 가장 큰 수보다 작거나 같은 경우
- 스택의 top이 현재 확인하고 있는 수와 같다면, top을 pop하고 ans에 -를 추가한다.
- 스택의 top이 현재 확인하고 있는 수와 같지 않다면, 더 이상 수열을 만들 수 없으므로 'NO'를 출력하고 종료한다. <- '스택에 push하는 순서는 반드시 오름차순을 지키도록 한다고 하자' 규칙 때문에
3. 최종적으로 만들어진 연산을 한 줄에 한 개씩 출력한다. 
- #46

[2023-06-04] sumin #46

---

BOJ/스택 수열/yerim.py

**백준 1874번: 스택 수열 (Silver 2)**
https://www.acmicpc.net/problem/1874
- 풀이 시간 : 1시간 15분
[첫 번째 접근]
1. 스택에 목표하는 숫자가 없다면(not in), 스택에 해당 숫자가 나올 때까지 push
2. 스택에 목표하는 숫자가 있다면(in) pop
3. pop 할 때 목표하는 숫자를 얻을 수 없다면 수열 만들기 불가능
=> 계속 시간 초과... in 연산 때문인 것 같음
[두 번째 접근]
1. 다음 숫자(target)가 현재 숫자(current_n)보다 작으면 스택에 target 숫자가 이미 있으므로 pop만으로 얻을 수 있음
2. 다음 숫자(target)가 현재 숫자(current_n)보다 크면 스택에 pop 하기 전 push 필요
3. pop 할 때 목표하는 숫자를 얻을 수 없다면 수열 만들기 불가능
=> 여전히 시간 초과... 하나하나 push, pop을 하면 안되는 건가?
도저히 시간 초과를 해결할 수 없어 답안 확인
Reference: https://hongcoding.tistory.com/39
[접근 방법]
- 느낌은 비슷하지만, 두 가지 디테일이 더 필요했다.
- stack의 마지막 숫자가 목표 숫자와 같은지 확인하고 pop을 해줘야 함.
- flag 사용. flag 미사용 시, NO가 출력된 이후 answer가 또 출력될 수 있음.
- #46

[2023-06-05] yerim #46

---

Programmers - 문제풀이/표현 가능한 이진트리/sumin.py

풀이시간: 1시간
- 30분 고민하고 재귀 구현하는 부분에서 자꾸 삑나서 방법만 참고
- 코드 작성하고 디버깅: 30분
<시간복잡도> : O(N)
**Solution**
1. 이진수로 변환   
2. 포화 이진트리 만들기    
3. 포화 이진트리가 제대로 성립하는지 확인    
- #47

[2023-06-08] sumin #47

---

BOJ/스택 수열/wooyeol.py

스택 수열
https://www.acmicpc.net/problem/1874
문제 해석
1. 잘못한 해석
스택을 사용하여 오름차순의 수열을 만들 수 있는가?
요소는 1~N까지의 정수
2. 1~N의 값이 순서대로 주어졌을 때 스택을 사용하여 주어진 수열을 구할 수 있는가?
- 현재 순서의 값이 입력값보다 작거나 같아질 때까지 'Push' 연산
- 이후 stack의 마지막 값이 입력값과 같아지면 'Pop' 연산
- 다음번 num을 입력받았으나 num 값이 target 보다 클 경우 수열 생성이 불가능 하기 때문에 'NO' 출력
접근법
무슨 알고리즘으로 풀이 할 수 있을까? -> 스택을 사용한 구현
고찰
'NO'를 'No'로 써놓고 30분동안 디버깅을 하였다. 피곤할 때는 자는게 좋을 것 같다.
- #46

[2023-06-05] wooyeol #46

---

BOJ/스택 수열/jisu.py

18:10 -> 18:50 문제 이해를 잘못해서 삽질을 좀.. 
`메모리 : 39908KB / 시간 : 192 ms`
임시 스택(`stack`)과 우리가 가지고 있는 1 ~ n까지의 수(`one2n`)를 머리속으로 왼쪽, 오른쪽에 배치해놓고 생각하면 이해하기 편함
one2n의 가장 찻번째 원소부터 stack에 넣어다가 빼어서 nums를 만들어야함
1. nums를 순회하며 one2n의 가장 첫 번째 원소부터 nums의 0, 1, ..., n번째 원소보다 같거나 작은 수를 다 스택에 삽입 (one2n은 1~n까지 차례대로 있으므로)
2. 1번 과정 이후 스택의 마지막 원소에는 항상 우리가 원하는 nums의 원소가 있어야함. 
2-1. stack[-1]이 nums의 n번째 원소와 같다면 pop 연산
2-2. 같지 않다면 nums의 수열을 애초에 만들 수 없었던 것, flag 변수를 False로 만들어 준다.
3. nums의 마지막 원소까지 순회를 마쳤을 때 flag 변수가 True이면 저장했던 연산 순서를 출력, False이면 NO 출력
- #46

[2023-06-04] jisu #46

---

Programmers - 문제풀이/표현 가능한 이진트리/jisu.py

`12:35 -> 1시간 가량 고민 후 풀이 참고`
numbers의 길이 <= 10000
numbers의 원소의 크기 <= 1,000,000,000,000,000
무조건 logn
1. 2진수로 변환 후 앞단에 0을 붙여 포화 이진 트리 크기(1, 3, 7, 15, ..., 2^n - 1)로 만들기
2. 재귀적으로 중위 순회 결과가 정상적인 포화 이진 트리를 만들어내는지 검사 => 여기서 부터 막힘
KEY : 이진 트리를 만족하기 위해서 자식 노드 위에는 항상 부모 노드가 존재해야 한다.
**이진수[mid] == '1'**
- #47

[2023-06-08] jisu #47

---

Programmers - 문제풀이/표현 가능한 이진트리/dohyun.py

풀이시간
- 약 30분 고민해보고 도저히 손도 안 떨어져서 레퍼런스를 참고해서 공부해보자고 생각
접근법
- numbers 의 원소의 크기가 10^15 -> 시간복잡도 무조건 고려
- 라고 생각했지만 이진수로 변환을 하기 때문에 생각보다 별로 안될 것이라고 생각
- Python 내장 bin 함수를 이용하면 십진수 값을 이진수 문자열로 돌려줌!
회고
- 진짜진짜 도저히 모르겠어서 레퍼런스 풀이를 여러 개 찾아봐도 도저히 모르겠음
- 코딩테스트 문제 풀면서 아예 문제 자체가 낯선 개념인게 처음이라 당황스럽다 ... 자료구조/알고리즘 개념이 없어서 그런가 ...
- #47

[2023-06-08] dohyun #47

---

Programmers - 문제풀이/표현 가능한 이진트리/wooyeol.py

표현 가능한 이진트리
https://school.programmers.co.kr/learn/courses/30/lessons/150367?language=python3
해결법 참조 : https://velog.io/@top1506/2023-KAKAO-표현-가능한-이진트리python
접근법
1. 주어진 수를 이진수로 변환하기
2. 이진수로 만들어진 수가 In-order 순회식이라고 생각하고 이진 트리 내용의 값을 검사하기
1. 이때 필요한 조건 : 현재 가지는 이진수의 자리수를 포화 포화 이진트리의 노드수와 같게 만들어주기
- With 0을 삽입하는 방식으로
3. 이진 트리를 순회하며 부모 노드가 0인데 자식노드가 1인 경우를 찾아서 반환
- #47

[2023-06-08] wooyeol #47

---

Programmers - 문제풀이/아방가르드 타일링/wooyeol.py

아방가르드 타일링
https://school.programmers.co.kr/learn/courses/30/lessons/181186
접근법
무슨 알고리즘으로 풀이 할 수 있을까? -> DP
- dp로 갯수의 패턴을 찾고 점화식을 세워 풀이
- 풀이 참고 (https://schini.tistory.com/entry/아방가르드-타일링-181186번-프로그래머스-Programmers)
- #57

[2023-06-12] wooyeol #57

---

Programmers - 문제풀이/아방가르드 타일링/dohyun.py

풀이시간
- 약 1시간 가량 풀이 후 레퍼런스 참고
- https://velog.io/@jinhoss/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4-%EC%95%84%EB%B0%A9%EA%B0%80%EB%A5%B4%EB%93%9C-%ED%83%80%EC%9D%BC%EB%A7%81python
- https://velog.io/@mechauk418/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4-%EC%95%84%EB%B0%A9%EA%B0%80%EB%A5%B4%EB%93%9C-%ED%83%80%EC%9D%BC%EB%A7%81-%ED%8C%8C%EC%9D%B4%EC%8D%ACDP
접근법
- 도형을 맞추는 알고리즘을 구현하는 건 말이 안된다고 판단
- 무조건 규칙이 있다고 생각했음 -> 규칙으로 재귀
- n이 4까지는 어찌저찌 구하겠는데 5부터는 도저히 감이 안잡힌다 ...
- 또한 n이 4일 때까지는 규칙을 도저히 못찾겠음
- 참조한 레퍼런스에서는 새로운 유형의 블록의 개수로 규칙을 정의하여 점화식 구성
- n=1 -> 1
- n=2 -> 2
- n=3 -> 5
- n=4,7,10 -> 2
- n=5,8,11 -> 2
- n=6,9,12 -> 4
- 최종적인 점화식은 $$A(X) = \sum_{i=1}^{X-1}{A(X-i) \times s(i)} + s(X)$$
- $$A(X) = A(X-1) + 2A(X-2) + 5A(X-3) + 2A(X-4) + 2A(X-5) + 4A(X-6) + \dots$$
- …

[2023-06-12] dohyun #57

---

Programmers - 문제풀이/아방가르드 타일링/yerim.py
Programmers - 문제풀이/표현 가능한 이진트리/yerim.py

**[프로그래머스 - 아방가르드 타일링](https://school.programmers.co.kr/learn/courses/30/lessons/181186)**
- 풀이 시간 : -
- 접근 방법 : 10분 동안 고민해봤는데 와 그냥 못풀 것 같아서 바로 풀이 확인했습니다..
- 참고 : https://velog.io/@jinhoss/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4-%EC%95%84%EB%B0%A9%EA%B0%80%EB%A5%B4%EB%93%9C-%ED%83%80%EC%9D%BC%EB%A7%81python
**[접근 방법]**
- n에 따라 타일링 할 수 있는 새로운 블록 개수를 계산해 보면, 일정한 규칙이 있음
- 따라서 새로운 블록 개수에 대해 점화식 작성 가능 (블로그 링크 참고)
- 점화식을 정리하여 행렬로 표현 가능
- 해당 행렬을 코드로 구현하여 구하고자 하는 새로운 블록 개수(A(X))를 계산 가능
- 근데 사실 아직도 이해가 다 안됐습니다,,, 넘 어렵네요,,,
- #57

[2023-06-12] yerim #57

---

BOJ/큐/dohyun.py

풀이시간
- 약 10분
접근법
- 문제를 읽어보니 deque 에서 전부 구현가능
- 제출 전까진 시간 복잡도가 문제일까? 라는 생각을 하긴 했지만 size 연산 제외 그럴 여지는 딱히 보이지 않았음
- 따라서 바로 deque 로 구현!
회고
- 나름 easy 했던 문제였던 것 같은데 그대로 따라가기만 한거라 다른 분들의 디테일이 궁금하네요!
- #58

[2023-06-14] dohyun #58

---

BOJ/큐/jisu.py

21:50 -> 22:00
명령의 수가 10000까지 주어질 수 있으므로 O(N)안에서 해결해야 할듯!
덱을 쓰려다 심심해서 Queue 클래스를 정의해보았습니다!
그러다보니 일단 pop 연산을 O(N)짜리로 구현해봤습니다
시간은 `48ms` 나왔는데 예전에 deque으로 문제 풀이한 기록 보니 `72ms`이네요. 이게 type hint의 힘..?
- #58

[2023-06-14] jisu #58

---

BOJ/큐/wooyeol.py

큐
https://www.acmicpc.net/problem/10845
접근법
무슨 알고리즘으로 풀이 할 수 있을까? -> 단순 구현
queue 자료형을 이해한다면 python deque을 사용하여 구현이 가능하다.
- #58

[2023-06-14] wooyeol #58

---

BOJ/큐/sumin.py

풀이시간: 3분
**input**
n: 명령의 수 (1 ≤ N ≤ 10,000)
시간복잡도: O(N)
- #58

[2023-06-14] sumin #58

---

BOJ/카드2/wooyeol.py

카드2
https://www.acmicpc.net/problem/2164
접근법
무슨 알고리즘으로 풀이 할 수 있을까? -> deque을 사용하여 O(1)연산을 반복 실행한다.
50만회가 최대이기 때문에 단순 구현이 가능하였고 이때에 pop, append 연산이 O(1)이어야한다.
따라서 deque를 사용하여 구현한다면 시간 초과가 걸리지 않는다.
len() 함수를 매번호출하지 않고 length를 기억하는 변수를 사용하였더니 시간이 (240 -> 212 ms)로 단축되었습니다.
- #69

[2023-06-17] wooyeol #69

---

BOJ/카드2/jisu.py

'''
16:30 -> 16:35
1 <= N <= 500,000 이므로 O(N) 안에 해결
'''
아래 과정을 카드가 1장 남을 때 까지 반복, deque 자료구조를 queue로 활용해 문제 풀이
- #69

[2023-06-17] jisu #69

---

BOJ/카드2/yerim.py

[백준: 카드2 (Silver 4)](https://www.acmicpc.net/problem/2164)
- 풀이 시간: 10분
- 접근 방법:
- popleft 활용을 위해 deque으로 구현
- #69

[2023-06-19] yerim #69

---

BOJ/카드2/sumin.py

풀이 시간: 3분
**input**
N: 정수 N(1 ≤ N ≤ 500,000)
**solution**
시간 복잡도: O(N) <- while문이 최대 n-1번 반복되기 때문에
문제 조건대로 구현하면 된다.
- #69

[2023-06-19] sumin #69

---

Programmers - 문제풀이/표 병합/sumin.py

시간: 1시간
**<조건>**
- 50x50의 표는 초기에 모든 셀이 비어있음
- 각 셀은 문자열 값을 가질 수 있고, 다른 셀과 병합될 수 있음
**<input\>**
commands: 실행할 명령어들이 담긴 1차원 문자열 배열 (1 ≤ commands의 길이 ≤ 1,000)
- UPDATE r c value
- UPDATE value1, value2
- MERGE r1 c1 r2 c2
- UNMERGE r c
- PRINT r c
**<solution\>**
구현 문제(문제가 어렵다기보다는 구현할 조건이 많아서 귀찮음.. 테케 13, 14에서 15분 넘게 쓴 것 같음)
- 어떤 자료형으로 접근할 것인가?
- 딕셔너리? 2차원 배열?
- 50x50이라 둘 다 TLE는 안 뜰거같아서 걍 딕셔너리로 풀이함
- 시간복잡도: O(commands의 크기 * N^2) -> 최대 1000 * 50 * 50 = 2,500,000
- 문제에 제시된 대로 구현하면 된다.
- 셀의 내용이 기록돼있는 표 딕셔너리(chart)와 병합 정보를 기록해둔 딕셔너리(merge) 각각을 만들어 사용
- 다른 사람들 풀이를 보다보니 대부분 union-find로 풀이했길래 union-find로도 풀어 볼 예정
- #70

[2023-07-03] sumin #70

---

Programmers - 문제풀이/표 병합/wooyeol.py

표 병합
https://school.programmers.co.kr/learn/courses/30/lessons/150366
접근법
무슨 알고리즘으로 풀이 할 수 있을까? -> merge를 할 때 연결 리스트와 같은 형태로 진행하기
commands 최대 1000번
find : avg - 2번
print : O(1)
update : O(2500) or O(1 + alpha)
merge : O(2500 + alpha)
unmerge : O(2500 + alpha)
- #70

[2023-07-03] wooyeol #70

---

Programmers - 문제풀이/표 병합/dohyun.py

풀이시간
- 약 1시간 30분 가량 풀다가 답지를 보는게 나을 것 같아서 기존 풀이와 가장 비슷한 풀이 참고
https://magentino.tistory.com/69
접근법
- r, c 는 좌표가 아닌 "번째" 를 말하고 있으므로 좌표로 해석하려면 1 을 빼줘야함
- 표를 어떻게 표현해야할까? -> 그냥 행렬로 생각하고 빈 값은 "NULL" 로 표현하기로 약속하자
- merge 를 어떻게 표현할까가 애매하다고 생각했는데, 값 뒤에 "_merged" 를 붙혀서 표기해보자고 생각
- 또한 merge 조건이 복잡하므로 실수하지않고 잘 구현하겠다 생각
- 전체적으로 복잡도가 적으므로 완전탐색 느낌으로 구현을 시작해도 될 것 같음
회고
- 인덱스를 관리하는 배열 (merged), 값을 관리하는 배열 (board)
- 각 배열을 따로 만들어서 해결한 점이 인상적 -> 해당 방법으로 Merge 를 해결할 수 있었음
- #70

[2023-07-03] dohyun #70

---

BOJ/덱/wooyeol.py

덱
https://www.acmicpc.net/problem/10866
접근법
무슨 알고리즘으로 풀이 할 수 있을까? -> 덱을 사용한 구현
고찰
python collections의 deque을 사용하여 각 명령어와 내장 메소드를 매핑해줌으로써 해결 할 수 있었습니다.
input 데이터를 입력 받을 때 '변수, *변수 = input().split()'을 사용한다면 커맨드와 인자를 받는 경우를 구분 할 수 있어 좋은 것 같습니다.
- #82

[2023-07-13] wooyeol #82

---

BOJ/덱/jisu.py

- collections 모듈의 deque을 활용하는 Deque 클래스를 문제에 맞는 wrapper 클래스로정의
- main 메서드에서는 주어지는 명령문에 조건에 맞게 eval 함수를 활용해서 간략하게 작성함
- #82

[2023-07-13] jisu #82

---

BOJ/덱/dohyun.py

풀이시간
- 5분
접근법
- deque 자료구조로 모두 풀이 가능
- 최대한 간단하게 쓰고 싶어 이항 연산자 사용
회고
- 덱 문제 계속 나오니까 뭔가 계속 똑같은 문제를 푸는 느낌이네요 ... ㅎ
- #82

[2023-07-13] dohyun #82

---

BOJ/덱/sumin.py

**풀이 시간**: 6분
주어진 대로 구현하면 된다.
문제의 이름처럼 deque 라이브러리를 사용해서 구현하면 앞, 뒤에 숫자를 넣고 빼는 작업을 O(1)에 할 수 있다.
**시간복잡도**: o(n)
- #82

[2023-07-13] sumin #82

---

Programmers - 문제풀이/정수 삼각형/jisu.py

풀이 시작 : 2023.08.08 23:32 
- n층의 삼각형에서 숫자의 개수는 (2^n)-1 개이다. 
- 따라서 모든 경우의 수 중 최대값을 구하고자 하면 나올 수 있는 경우의 수는 ((2^n)-1)! -> 여기서 완전탐색으로 최대값을 찾기에는 너무 연산량이 많다.
- 가장자리에 있는 수들은 하나의 수가 더해지고, 안쪽의 수 들은 두 경우의 수 중 큰 경우의 수를 받을 것이다. 그러면 큰 경우만 받아서 저장하자(dp)
- 그러면 가장 마지막 층에서 가장 큰 원소만 구하면 거쳐간 숫자의 최대값을 구할 수 있다.
- 사실 dp 문제에서 많이 본 유형이었기 때문에 바로 떠올릴 수 있었다.
풀이 완료 : 2023.08.09 00:01
- #95

[2023-08-11] jisu #95

---

Programmers - 문제풀이/타겟 넘버/sumin.py

**풀이시간**: 20분
**<제한사항>**
- 2 <= 숫자 개수(n) <= 20
- n개의 음이 아닌 정수
- 숫자의 순서는 바꾸지 않고, +/- 둘 중에 하나를 사용
**\<Solution>**
- 연산자(+/-) 둘 중 하나를 n번 **선택** 하는 문제이기 때문에 재귀를 사용
**<시간복잡도>**
O(2^n): 연산자(+/-)둘 중 하나를 n번 선택하는 경우
-> n이 최대 20이기 때문에 2^20 = 1,048,576 연산횟수로 시간 내 통과 가능
- #96

[2023-08-11] sumin #96

---

BOJ/쇠막대기/wooyeol.py

쇠막대기
https://www.acmicpc.net/problem/10799
풀이시간
20:37 ~ 21:17(40분)
접근법
무슨 알고리즘으로 풀이 할 수 있을까? 스택
괄호 표현식을 상대할 때는 닫힘 연산이 나오기 까지 현재 괄호를 bucket에 담아 두었다가 꺼내는 Stack을 자주 사용해왔습니다.
그래서 이번 문제도 동일하게 괄호 표현식의 괄호를 검사하며 풀이를 하기 위해 bucket(stack 자료구조)을 사용하여 풀이하였습니다.
하지만 이번에는 한 쌍의 "()" 괄호인지 "(", ")" 인지에 따라서 연산이 달라져야했기에
직전의 기호를 기억하는 state 라는 bool 변수를 사용하여 기록하는 방식을 통해서 구현 할 수 있었습니다.
이후 닫힘 괄호를 맞이하였을 때 state를 확인하여 현재 bucket에 담긴 쇠 막대기의 수를 더하거나 절단되고 남은 하나의 쇠 막대기를 더해주거나 둘 중에 하나의 연산을 해주었습니다.

[2023-08-14] wooyeol #109

---

BOJ/괄호의 값/wooyeol.py

괄호의 값
https://www.acmicpc.net/problem/2504
풀이시간
21:24 ~ 12:18 (대략 6시간)
접근법
무슨 알고리즘으로 풀이 할 수 있을까? 스택
조건 1: ‘()’ 인 괄호열의 값은 2이다.
조건 2: ‘[]’ 인 괄호열의 값은 3이다.
조건 3: ‘(X)’ 의 괄호값은 2×값(X) 으로 계산된다.
조건 4: ‘[X]’ 의 괄호값은 3×값(X) 으로 계산된다.
조건 5: 올바른 괄호열 X와 Y가 결합된 XY의 괄호값은 값(XY)= 값(X)+값(Y) 로 계산된다.
접근 1 : 괄호를 검사하여 사칙연산의 표현식으로 변환을 진행하고 해당 표현식을 적절한 타이밍에 연산을 진행하여 정답을 도출
접근 2 : 연산식에 분배법칙을 적용하여 전개하였을 때 하나의 항들을 우선적으로 계산하는 방식으로 괄호 표현식을 풀이
- 여는 괄호 종류에 따라 res 항에 2,3을 곱해주어 분배법칙이 적용된 값을 계산합니다. 
- 괄호가 닫힐 경우 한 쌍의 연속된 경우였는지 확인 후 맞다면 분배법칙이 적용된 값을 answer 항에 더해주고 아니라면 res에 다시 해당 2,3 값을 나눠줍니다.
- 분배법칙 예시) (2+3x3)x2 + 2x3 = 2x2 + 2x3x3 + 2x3
1. 2x2
2. 2x3x3 (2를 한 번 나눠주고 3을 두번 더 곱해줌)
3. 2x3 (3을 한 번 나눠줌)

[2023-08-14] wooyeol #110

---

Programmers - 문제풀이/타겟 넘버/wooyeol.py

타겟 넘버
https://school.programmers.co.kr/learn/courses/30/lessons/43165
접근법
무슨 알고리즘으로 풀이 할 수 있을까? -> 2^50이라 완전탐색이 불가능 그렇기에 BFS/DFS 탐색을 고려
해당 값에 - / + 부호를 붙일지에 따라 이진 트리로 그래프를 생각할 수 있음
모든 그래프를 생각할 직전에 계산된 값들만 기억하게 한다면 메모리 효율도 높일 수 있다.
다른 풀이를 찾아보던 중 메모이제이션을 사용하여 속도를 개선하는 답을 확인 할 수 있었고 적용해보았는데
속도 개선이 많이 되었다.

[2023-08-11] wooyeol #96 

---

BOJ/괄호의 값/sumin.py

**풀이시간**: 30분
**\<input>**
- 1 <= 문자열의 길이 <= 30
- 단순 구현 문제, 다만 예외처리를 잘해줘야 됨!!
- 괄호값을 모두 더해줘야 하기 때문에 올바른 괄호 쌍이 닫힐 때마다 더해준다.
- 여는 괄호의 경우 항상 stack에 추가해주고, 곱해질 값을 저장해 둘 num 변수를 둔다.
- (의 경우 괄호 안의 값은 모두 *2가 되기 때문에 num *= 2를
- [의 경우 괄호 안의 값은 모두 *3이 되기 때문에 num *= 3를 해준다.
- 닫는 괄호의 경우 올바르지 못한 괄호쌍이 되거나, 올바른 괄호쌍이 되거나 두 가지 경우가 있다.
1\) 올바르지 못한 괄호쌍
- stack이 비어있거나 stack의 top이 자신의 짝 괄호가 아닌 경우    
2\) 올바른 괄호쌍
- 직전 괄호가 자신의 짝 괄호인 경우 -> ans 값 갱신
- 모든 괄호값을 순회한 후 stack이 비어있으면 ans값 출력, stack이 비어있지 않다면 0 출력
- ex) [[]
**<시간 복잡도>**
O(N)
- #110

[2023-08-14] sumin #110 

---

BOJ/불!/wooyeol.py

불!
https://www.acmicpc.net/problem/4179
풀이시간
20:10 ~ 03:00 오답 (약 7시간)
1 <= R <= C <= 1000
1000 by 1000 = 1,000,000
접근법
무슨 알고리즘으로 풀이 할 수 있을까? BFS or DFS
- 불은 1분에 4칸씩 번짐
- 사람은 1분에 한 칸씩 움직임
맵에서 끝까지 어디로든 끝까지 간다면 탈출 성공 아니면 실패
불을 기준으로 bfs 진행하고 사람을 기준으로 bfs를 진행하며 사람이 테이블 밖으로 무사히 나가진다면 결과가 바로 반환 (최소 값을 찾기 때문에)
지훈이 밖으로 나갈 수 있다면 바로 출력하고 탐색 이후에도 나가지 못했다면 불가능으로 판단 후 반환
이때에 지훈이 지나가려는 장소에 불이 온적이 있는지 확인하고 자기보다 빨리 혹은 같은 시간에 지나갔다면 지훈은 지나갈 수 없음
- 다음의 알고리즘을 bfs를 두 번 사용하여 풀이 할 수 있었습니다.

[2023-08-16] wooyeol #111 

---

BOJ/불!/jisu.py

풀이 시작 : 2023.08.15 21:00
- 불은 4방향으로 확산 되며, 지훈님도 상하좌우로 이동할 수 있다.
- BFS를 활용해서 지훈님과 불의 각 time step 별로 이동 경로를 정의한다.
- BFS를 위한 지훈님과 불의 queue를 별도로 정의해야 하며, queue에는 다음 time step에서 이동 경우의 좌표와 timestep을 함께 관리한다.
-  지훈님과 불의 초기 위치 판별을 위한 로직 필요, 불은 여러 군데서 초기에 발생할 수 있다.
-  불이 timestep 마다 번지므로 이를 어떻게 관리할지 고려 필요
- visited의 각 좌표 별 원소를 [방문 여부, 불 탄 time step]으로 표시하면 될 듯
- 그러면 지훈님은 아직 방문하지 않은 곳(visited[0])과 현재 시점에서 아직 불에 타지 않은 곳 (timestep < visited[1])에 갈 수 있다.
- 불과 지훈님이 동시에 특정 지점에 닿으면 안되므로, 일단 불부터 이동시켜야 함
- 그리고 큐에는 timestep마다 갈 수 있는 곳이 담기는데, 각 timestep마다 지훈님이 갈 수 있는 곳, 불이 갈 수 있는 곳이 다르게 담긴다.
- 별도의 변수를 둬서 시간 동기화가 필요하다.
풀이 완료 : 2023.08.15 23:00
- #111

[2023-08-16] jisu #111

---

BOJ/종이의 개수/jisu.py

풀이 시작 : 2023-08-18 11:03
N은 3^k 꼴로 주어짐
3^k * 3^k 를 순회하여 모두 같은 수인지 확인 -> 같다면 해당 수 종이 += 1
-> 같지 않다면 9등분 -> 3^(k-1) * 3^(k-1) 를 순회하며 반복
-> 이전 문제와 마찬가지로 각 영역에 해당하는 인덕스를 적절하게 조절하여 재귀해줘야 함
풀이 완료 : 2023-08-18 11:45 (풀이 소요 시간 : 42분)

[2023-08-18] jisu #114

---

BOJ/Z/wooyeol.py

Z
https://www.acmicpc.net/problem/1074
풀이시간 07:00 ~ 07:25(25분)
1 <= N <= 15
0 <= r,c < 2**N
접근법
무슨 알고리즘으로 풀이 할 수 있을까? 재귀적 구현
제 4사분면으로 분리하고 각 사분면의 시작점을 기준으로 이전 값들을 더해주는 연산을 진행한다면
재귀로 편하게 나타낼 수 있다.
그렇기에 BaseCondition은 N이 0일 때 0을 반환하게 한다.
가장 작은 N은 0이고 이는 r,c에 관계없이 순서가 0번째임을 나타내는 것이다.
그렇다면 N == 1이라면,
size = 2 **(n-1)일때 size=1
x * (1 * 1) + 0 이다. (x는 사분면 - 1) 
이다.

[2023-08-18] wooyeol #113

---

Programmers - 문제풀이/k진수에서 소수 개수 구하기/dohyun.py

풀이시간
- 약 40분
접근법
- N = 100만 -> O(NlogN) / O(N)
- 네가지 경우를 줬지만 생각해보니 이건 사실상 경우를 나누라는 뜻이 아니라 0 사이에 껴있는 소수를 찾으라는 말임
- 테케 1 문제에서 시간초과가 났음
- 아무리 생각해봐도 시간을 줄일 부분은 소수 확인 부분 밖에 없다고 판단
- 옛날 옛적 소수를 판별하는 데 효율적인 방법이 있었다고 기억이 남 -> 도저히 뭔지 기억 안나서 구글링 했습니다 ..ㅎ -> 바꿨더니 시간초과 해결!
회고
- 십진수에서 n진수 변환하는 법을 까먹었네요..ㅎㅎ
- 소수, 진수에 대한 문제들을 몇번 봤던 것 같아서 이번 기회에 까먹은 개념들을 다시 톺아봐야할 것 같음
- #137

[2023-08-21] dohyun #137

---

Programmers - 문제풀이/전화번호 목록/jisu.py

풀이 시작 : 2023-08-20 12:49
N은 1,000,000 이하이므로 O(NlogN)안에 해결해야한다.
phone_book에 대해 정렬을 수행하면 아스키 코드 순 -> 짧은 순으로 정렬이 되므로,
만약 한 번호가 다른 번호의 접두어라면, i-1번째 인덱스의 번호가 i번째 번호의 접두어일 것이다.
풀이 완료 : 2023-08-20 13:00 (풀이 시간 : 11분)

[2023-08-21] jisu #136

---

Programmers - 문제풀이/k진수에서 소수 개수 구하기/jisu.py

풀이 시작 : 2023-08-20 13:24
1 <= n <= 1,000,000 이므로, 1,000,000을 2진수로 바꿨을 때 길이가 M 이라면 
1 <= M <= 20 -> 그냥 일단 구현하면 되겠다.
n을 k진수로 바꾼 후 0을 기준으로 split
가장 왼쪽, 오른쪽 원소 -> P0, 0P 검사 : 그냥 가장 왼쪽, 오른속 원소가 소수인지
중간 원소 -> 0P0 검사 : 가운데 원소가 소수인지
원소가 하나일 경우 -> P 검사 -> 해당 원소가 소수인지
===> 결국 0을 split 한 리스트에서 소수 개수를 세면 된다.
풀이 완료 : 2023-08-20 13:48 (풀이 시간 : 24분)

[2023-08-21] jisu #137

---

Programmers - 문제풀이/전화번호 목록/wooyeol.py

전화번호 목록
https://school.programmers.co.kr/learn/courses/30/lessons/42577
풀이시간 
23:35 ~ 24:01
접근법
무슨 알고리즘으로 풀이 할 수 있을까? -> 문자열 내장 함수
1~100만개의 번호중 한 번호가 다른 번호의 접두어인 경우가 있는지 확인
1. 컨텐츠를 길이 순으로 정렬 + 이중 For문을 사용하여 확인
2. 숫자순으로 정렬 + startwith로 접두어를 검사

[2023-08-21] wooyeol #136

---

Programmers - 문제풀이/네트워크/wooyeol.py

네트워크
https://school.programmers.co.kr/learn/courses/30/lessons/43162
풀이시간 
22:40 ~ 23:13(33분)
문제 조건
컴퓨터의 개수(n) : 1 ~ 200
시간 복잡도 : O(n^2)
접근법
무슨 알고리즘으로 풀이 할 수 있을까? -> BFS or DFS를 사용하여 네트워크의 개수 파악하기
- 전체 컴퓨터를 대상으로 BFS 탐색을 진행한다.
- 컴퓨터를 하나씩 확인하며 방문하지 않은 컴퓨터일 경우 탐색을 진행
- 해당 컴퓨터 방문 처리 + 현재 컴퓨터와 네트워크를 형성하는 컴퓨터들을 탐색하기 위한 BFS 진행
- 해당 컴퓨터를 기점으로 발생한 네트워크가 확인된 것이기 때문에 네트워크 개수 +1

[2023-08-23] wooyeol #143

---

Programmers - 문제풀이/최고의 집합/jisu.py

풀이 시작 : 2023-08-21 11:11
1 <= n <= 10,000 이므로 O(NlogN)으로 구현해야 한다.
중복집합임에 주의, 각 집합의 원소는 중복될 수 있음
최고 집합이 존재하지 않는 경우는 S가 합으로 만들어지지 않는 집합 => n보다 s가 더 작은 경우
최대한 S를 큰 수로 토막 내는 것이 각 원소의 곱이 최대가 되는 집합이다.
1. S를 N으로 나눈 몫을 m이라고 할때 집합에 m을 추가
2. S-=m, N-=1
3. N개의 수가 모일 때까지 반복
4. 정렬 후 반환
풀이 완료 : 2023-08-21 11:28 (풀이 시간 : 17분)

[2023-08-23] jisu #142

---

Programmers/야근 지수/wooyeol.py

야근 지수
https://school.programmers.co.kr/learn/courses/30/lessons/12927
풀이시간 
00:33 ~ 01:16 (43분)
문제 조건
n : 1 ~ 1,000,000 이하 O(nlogn)가능 
works의 길이 : 1 ~ 20,000
works의 각 값 : 1 ~ 50,000
시간 복잡도 : O(n+k) 
n : works의 길이 20,000
k : works의 최대 값 50,000
접근법
무슨 알고리즘으로 풀이 할 수 있을까? -> 계수 정렬
예외처리 : 남은 작업량이 퇴근까지 남은 시간보다 같거나 적으면 야근 피로도는 0
- 최선의 값은 남은 작업량의 모든 값을 전체적으로 줄여주는 것이다.
- 계수정렬을 사용해야한다. (Counter를 사용)
- Counter 내에 있는 가장 큰 값을 기준으로 작업량을 분산시켜(1씩 뺄셈을 해주어) 전체적인 피로도를 낮춰야한다.
1. 가장 크기가 큰 작업의 개수가 퇴근까지 남은 시간보다 작을 경우
- 작업량을 분산시키고 남은 시간을 갱신
- ex)
4시간짜리 작업이 2개에 3시간짜리 작업이 3개일 경우 (n = 3)
3시간짜리 작업을 4시간짜리 작업의 개수만큼 늘리고
퇴근까지 남은 시간을 1시간 빼주고 4시간짜리 작업은 0으로 변경
2. 가장 크기가 큰 작업의 개수가 퇴근까지 남은 시간보다 크거나 같을 경우
- 작업량을 분산시키고 남은 시간을 갱신
- ex)
4시간짜리 작업이 2개에 3시간짜리 작업이 3개일 경우 (n = 1)
4시간짜리 작업의 개수에서 n 만큼 제외하고
3시간짜리 작업을 4시간짜리 작업의 개수만큼 …

[2023-08-28] wooyeol #145

---

Programmers/압축/dohyun.py

풀이시간
- 46분
접근법
- n 이 1000 이하 -> O(N^2) 이상의 풀이도 가능
- 특정 알고리즘을 예시까지 친절히 주었고 시간복잡도 충분 -> 일단 구현해보자
- 초기 단어사전을 딕셔너리로 구현하려했지만 리스트로해도 문제없음 -> 리스트로 구현
- 업데이트되는 단어가 가변성을 띄는 것을 주의
- 시간복잡도가 충분하기 때문에 반복문으로 구현
회고
- 예제를 친절하게 제공해줘서 풀이하기가 비교적 수월했음
- 이후에 궁금해서 검색해보니 해시 테이블로 구현되어있는 딕셔너리를 사용하는게 시간복잡도를 더 줄일 수 있는 방법이었던것 같음
- #144

[2023-08-28] dohyun #144

---

BOJ/암호 만들기/jisu.py

풀이 시작 : 2023-08-29 10:50
3 <= L <= C <= 15 이므로 N! 이전 알고리즘까지는 가능할 것 같다.
- 암호가 알파벳의 오름차순으로 배열되어있을 것 -> 갖고 있는 알파벳 리스트 정렬
- 이후 순서대로 인덱스 C까지 순회하며, 알파벳을 가져가는 경우, 안가져가는 경우로 분기(재귀)
- 이때 자음 모음 개수를 관리해야 하는데, 매번 길이가 L이 될 때마다 문자을열 탐색하는 것은 비효율 적이라고 판단 -> 매개변수로 관리
- 자음(모음)이 추가될 경우 자음(모음)) 매개변수 +1,
- 최종적으로 C까지 순회를 마치고 길이가 L인 password에 대해서 자음&모음 개수를 만족하는 패스워드를 출력
풀이 완료 : 2023-08-29 11:15 (풀이 시간 : 25분)

[2023-08-30] jisu #161

---

BOJ/N-Queen/dohyun.py

풀이시간
- 1시간 30분 (이후 해결 실패로 답지 참고)
접근법
- 시간복잡도 O(N^3) 까지도 가능? -> 잘 모르겠음 ㅠㅠ
- 퀸 하나를 놓을 수 있는 최대 경우의수 : 15*15
- 퀸의 개수 최대 15개
- 즉 최대 경우의수 15**3
- 그래프 탐색 문제 -> DFS/BFS 로 접근 가능할 것 같음
- 퀸을 하나씩 두어가며 경우의 수를 탐색하므로 DFS 가 적절할 것이라 판단
- 재귀가 아닌 방식을 활용해보고 싶어서 풀다가 포기 ㅠㅠ
회고
- DFS/BFS 가 조금은 익숙해진 느낌이지만 아직 구현하는 연습을 더 많이해야겠다고 느낌
- DFS/BFS 원리를 조금 더 면밀히 이해할 필요가 있음
- 백트래킹? 개념은 몰랐지만 실패한 본인 풀이에서 백트래킹 개념으로 풀이하고 있었음
- Q. 따로 공부하는 개념이 아니라 문제를 많이 풀어보는게 좋을까요?!
- 행을 고정하여 탐색을 시작하는 것이 중요했던 것 같음
- #160

[2023-08-30] dohyun #160

---

Programmers/n진수 게임/dohyun.py

풀이시간
- 50 분
접근법
- 주어진 변수들의 범위가 매우 적은 편 -> 구현에 집중
- 숫자를 계속 해서 빼는 작업을 해야함 -> 큐를 활용하면 시간복잡도에서 장점이 많을 것이라 판단
- appendleft : 진법 변환할 때 따로 정렬하지 않아도 됨
- popleft : 글자를 빼낼 때 유용
회고
- 다른 사람의 풀이를 보니 본인의 코드에서 차례를 초기화하는 과정을 슬라이싱을 잘 활용해서 조금 더 코드를 간결하게 한 것 같음
- 개인적으로도 이 부분을 조금 더 간결하게 하고 싶어 고민했는데 ㅠㅠ 머리만 굴리지말고 조금 더 적어보면서 고민하기
- #181

[2023-09-06] dohyun #181

---

Programmers/주차 요금 계산/dohyun.py

풀이시간
- 약 37분
접근법
- records 의 길이가 1000 이하 -> 시간 복잡도 고려 X
- 시간:분 포맷을 분 단위로 변환해야 편할 듯함
- 출차 기록이 없는 친구들이 조금 까다로울 듯 한데, IN 개수와 OUT 개수가 안맞으면 23:59 출차를 추가하면 될듯
- 이를 차량번호의 출차기록의 length 가 홀수인지 체크함으로서 구함
- 딕셔너리를 만들어 키값으로 차량번호를 넣으면 키값으로 정렬된 딕셔너리를 통해 반복문으로 풀 수 있을 듯함
회고
- 시각이 기본적으로 정렬되어 있어서 단순 append 나 출차 기록 예외처리 등이 수월했던 것 같음
- 중간중간 잔고장(?) 이 나서 시간이 조금 더 오래걸렸던 것 같은데 해볼만하다고 느낄수록 꼭 집중 놓지말기
- #182

[2023-09-06] dohyun #182

---

Programmers/주차 요금 계산/jisu.py

풀이 시작 : 2023-09-04 23:40
- 문제 조건
- records의 길이는 1,000 이하이므로, n^2까지 고려해봐도 될 것 같다.
- 문제 풀이
- 입차 시 dict에 입차 내역을 기록, 출차 시 dict의 내역을 바탕으로 시간 계산
- 시간은 차번 별 시간을 기록할 별도의 dict 활용
- 하루 동안의 모든 주차 내역을 합산 후 요금을 계산하여야 함.
- 최종적으로 합산 된 주차 시간으로 요금 계산 후, 차번 오름차순으로 요금 반환
풀이 완료 : 2023-09-05 00:40(1시간 소요)

[2023-09-06] jisu #182

---

Programmers/n진수 게임/wooyeol.py

n진수 게임
https://school.programmers.co.kr/learn/courses/30/lessons/17687
풀이시간 
22:25 ~ 11:30 (1시간 5분)
문제 조건
2 ≦ n ≦ 16
0 < t ≦ 1000
2 ≦ m ≦ 100
1 ≦ p ≦ m
시간 복잡도 : 
O(m(게임에 참가하는 인원) * t(미리 구할 숫자의 갯수))
O(mt)
접근법
무슨 알고리즘으로 풀이 할 수 있을까? -> 구현
- 처음에는 n진수의 첫자리 숫자들로 만들었다고 착각하고 풀었다가 제출하다보니 case3번이 이상한 것을 느끼고 재풀이 진행
1. 정수를 증가시키며 n진수의 표현으로 변환한다.
2. n진수의 표현 중에서 튜브의 순서인 숫자만 answer에 추가한다.

[2023-09-06] wooyeol #181

---

Programmers/주차 요금 계산/wooyeol.py

주차 요금 계산
https://school.programmers.co.kr/learn/courses/30/lessons/92341
풀이시간 
10:31 ~ 11:05 (34분)
문제 조건
1 <= R(records) <= 1000
시간 복잡도 : 
O(R(레코드 검사) + R(출차 시간이 안 적혀진 차량) + R(정렬) + R(차량별 주차 요금 계산))
O(4R) : 최대 O(4000)
접근법
무슨 알고리즘으로 풀이 할 수 있을까? -> 구현
1. 방문한 시간을 체크하고 출차한 시간을 체크하여 테이블에 등록 후 출차 시 주차 시간 업데이트
- 출차 기록이 없는 차량은 23:59분 기준으로 출차 처리
2. 차량별 주차 시간을 계산하여 주차 요금 계산

[2023-09-06] wooyeol #182

---

Programmers/단어 변환/jisu.py

풀이 시작 : 2023-09-05 13:30
- 단어의 길이 10 이하 -> 단어룰 순회하는 과정이 포함될 수 있음
- words의 단어는 50개 이하 -> 완전 탐색(50!)은 불가능 하다.
- begin에서 알파벳을 하나만 바꿔서 변환할 수 있는 word로 변환 (재귀, 백트래킹 활용)
- 두 문자열의 다른 문자의 개수를 카운트하는 로직 필요
- 아직 변환되지 않았고, 다른 문자의 개수가 하나인 경우만 다음 word로 재귀 가능
- target으로 변환된 경우 카운트 반환(카운트는 매개변수로 관리)
- 모든 경우를 리스트에 담아서 최종적으로 최소 카운트를 반환
- 리스트에 담긴 카운트가 없을 경우, 변환될 수 없는 것이므로 0을 반환
풀이 완료 : 2023-09-05 13:55 (풀이 시간 : 25분)

[2023-09-08] jisu #184

---

Programmers/더 맵게/wooyeol.py

더 맵게
https://school.programmers.co.kr/learn/courses/30/lessons/42626?language=python3
풀이시간 
21:06 ~ 21:32(26분)
문제 조건
2 <= len(scoville) = L <= 1,000,000
0 <= K <= 1,000,000,000
시간 복잡도 : 
O(L + (L-1) * 2 * logL) = O(1,000,000 + 999,999 * 2 * 1000) = O(2,000,998,000)
O(LlogL)
접근법
무슨 알고리즘으로 풀이 할 수 있을까? -> 힙
1. 최소힙을 구현하고 O(N)
2. 힙의 root가 K 이상인지 확인하고 맞다면 섞은 횟수 반환
3. 음식의 갯수가 2이상이면 스코빌 지수 섞기 연산 진행
- 스코빌 지수 섞기 연산 => 섞은 음식의 스코빌 지수 = 가장 맵지 않은 음식의 스코빌 지수 + (두 번째로 맵지 않은 음식의 스코빌 지수 * 2)
4. 음식이 하나만 있을 경우 불가능하기 때문에 -1 반환

[2023-09-08] wooyeol #183

---

Programmers/단어 변환/wooyeol.py

단어 변환
https://school.programmers.co.kr/learn/courses/30/lessons/43163
풀이시간 
23:00 ~ 00:20 (1시간 20분)
문제 조건
3 <= W : 단어의 길이 <= 10
3 <= N : len(words) <= 50
시간 복잡도 : 
O(N * W(dfs 탐색) * N(재귀문 최대 Depth))
O(W*N^2) = O(25,000)
접근법
무슨 알고리즘으로 풀이 할 수 있을까? -> DFS
- 예외처리 : target이 words 안에 없다면 0을 반환
1. dfs 탐색을 사용하여 백 트래킹을 사용한다.
1-1. Base Condition 탐색 노드와 target 값이 같다면 정답에 count 추가하기
1-2. is_similar를 통해 두 단어가 한 알파벳 차이인지 확인 및 방문한 단어인지 검사
- 다음 단어들 확인

[2023-09-08] wooyeol #184

---

BOJ/연속합/wooyeol.py

연속합
https://www.acmicpc.net/problem/1912
풀이시간
00:57 ~ 01:44 (47분)
문제 조건
1 <= N <= 100,000
시간 복잡도 : O(N)
접근법
무슨 알고리즘으로 풀이 할 수 있을까? -> DP
DP 테이블 : 현재 인덱스까지 중에서 가장 높은 값 저장하는 테이블
DP 테이블을 업데이트하며 최대 값 업데이트

[2023-09-11] wooyeol #204

---

BOJ/연속합/sumin.py

**풀이 시간**: 10분
**\<input>**
- n(1 ≤ n ≤ 100,000)
- n개의 정수로 이루어진 수열(수는 -1,000보다 크거나 같고, 1,000보다 작거나 같은 정수)
D[i] : i번째 수로 끝나는 가장 큰 연속합
1) i-1번째 수의 연속합에 포함되는 경우
- D[i-1] + A[i]
2) 새로운 연속합을 시작하는 경우
- A[i]
D[i] = max(D[i-1]+A[i], A[i])
**<시간복잡도>**
O(N)

[2023-09-11] sumin #204 

---

BOJ/LCS/sumin.py

**풀이 시간**: 35분
**\<input>**
두 문자열
- 문자열은 알파벳 대문자(최대 1000글자)
d[i][j]: word1의 i까지, word2의 j까지 있을 때 LCS(최장 공통 부분 수열)의 길이
1) word1[i] == word2[j]
- d[i][j] = d[i-1][j-1] + 1
2) word1[i] != word2[j]
- d[i][j] = max(d[i-1][j], d[i][j-1])
**<시간 복잡도>**
o(N^2)

[2023-09-11] sumin #205

---

Programmers/더 맵게/dohyun.py

풀이시간
- 약 30분
접근법
- 스코빌의 길이는 최대 백만 -> O(N) 에 가깝게 해결해야함
- 최대, 최소를 넣었다 뺐다 -> 힙을 이용하면 되겠다!
회고
- 수민님이 저번에 보여주신 힙이 기억에 나서 풀 수 있었습니다!!!
- #183

[2023-09-08] dohyun #183

---

BOJ/LCS/jisu.py

풀이 시작 : 2023-09-10 18:50
- st1과 st2 각각의 문자에 대응하는 matrix(dp 테이블)를 그리기
-----------------
_ A C A Y K P
C 0 1 1 1 1 1       -> A C A Y K P 에서 C 까지 고려했을 때 LCS 길이
A 1 1 2 2 2 2       -> A C A Y K P 에서 C A 까지 고려했을 때 LCS 길이 
P 1 1 2 2 2 3
C 1 2 2 2 2 3
A 1 2 3 3 3 3
K 1 2 3 3 4 4       -> A A C Y K P 에서 C A P C A K 까지 고래했을 때 LCS 길이
-----------------
- 규칙이 보임
- [r][c]에 대응하는 두 문자열의 문자가 같을 경우 왼쪽 위 대각선([r-1][c-1])에서 +1이 증가함
- [r][c]에 대응하는 두 문자열의 문자가 다를 경우 왼쪽([r][c-1]), 위쪽([r-1][c]) 중 큰 값이 옴
- r, c가 각각 0일 때에 대한 예외 처리
- 그냥 임시로 행, 열 하나씩 늘려서 처리하면 동일하게 로직 적용 가능
풀이 완료 : 2023-09-10 19:45(풀이 시간 : 55분)

[2023-09-11] jisu #205

---

BOJ/잃어버린 괄호/dohyun.py

풀이시간
- 약 30분
접근법
- 입력으로 주어지는 수의 길이 <= 50 -> 구현에 집중
- 값을 최소로 만들어야 한다 -> - 뒤의 값을 괄호를 통해 최대한 크게 만들어야 함 -> 그리디
회고
- 처음에는 str, int 가 섞인 상태로 진행했는데 같은 자료형(정수)로 한꺼번에 변환하는 방법이 훨씬 효율적인 것 같음
- 정수로 반환하는 과정에서 최대한 내장함수를 쓰려다가 조금 버벅거림 ...
- 풀고나서 드는 생각이 한꺼번에 정수로 변환해놓고 시작하지말고 반복문으로 변환해가면서 연산하는 방법이 조금 더 빠르긴 할 것 같다
- #206

[2023-09-13] dohyun #206

---

BOJ/수 이어 쓰기 2/wooyeol.py

수 이어 쓰기 2
https://www.acmicpc.net/problem/1790
풀이시간
21:59 ~ 22:49 22:55 ~ 24:16 (2시간 11분)
문제 조건
1 <= N <= 100,000,000
1 <= K <= 100,000,000
시간 복잡도 :
O(9 * 9 + 9)
접근법
무슨 알고리즘으로 풀이 할 수 있을까? -> 수학
1. 전체 N이 가질 수 있는 자리 수 확인
- 주어진 N에 자리 수(min_square == 자리 수를 10의 승수로 표현) 확인 및 10**x을 뺀 남은 정수의 값(extra) 확인
- 현재 N까지 숫자를 이어 붙였을 때 생기는 자리 수 확인
- 실제 자리수 * (10**실제 자리수 - 10**(실제 자리수 - 1))의 누적합
2. 만약 N의 최대 자리수 보다 k가 크다면 -1
3. 아니라면 K를 real number로 변경해주고 해당 값의 몇 번째 자리의 숫자를 반환 하는지 확인
ex) 
5 5
min_square : 0 , extra : 5
k_to_number : 5
5
20 23
min_square : 1 , extra : 11
k_to_number : 16
6

[2023-09-15] wooyeol #209

---

BOJ/골드바흐의 추측/jisu.py

풀이 시작 : 2023-09-14 16:32
- 에라토스테네스의 체를 활용해 10000 이하의 소수를 모두 구해 놓기
- 두 소수의 차이가 가장 작은 골드바흐 파티션 찾기
풀이 완료 : 2023-09-14 16:58 (풀이 시간 : 26분)

[2023-09-15] jisu #208

---

Programmers/게임 맵 최단거리/wooyeol.py

게임 맵 최단거리
https://school.programmers.co.kr/learn/courses/30/lessons/1844
풀이시간 
20:25 ~ 20:37 (12분)
문제 조건
Maps = N x M
1 <= N <= 100
1 <= M <= 100
시간 복잡도 : 
O(N * M) = O(10,000)
접근법
무슨 알고리즘으로 풀이 할 수 있을까? -> BFS
전형적인 BFS 알고리즘을 사용한 풀이

[2023-09-18] wooyeol #236

---

Programmers/게임 맵 최단거리/dohyun .py

풀이시간
- 약 20분
접근법
- 그래프 탐색, 최단거리 -> BFS
회고
- 기본적인 문제, 행과 열 헷갈려서 버벅거리지말고 차분히 풀자!
- #236

[2023-09-18] dohyun #236

---

Programmers/오픈채팅방/jisu.py

풀이 시작 : 2023-09-19 10:40
- record의 길이는 100,000 이하이므로 O(NlogN) 이하의 알고리즘을 설계해야 한다.
- 채팅방 입/퇴장 시 이름 메시지 출력
- 이름바꿔 들어오면 기존 메시지 이름도 바뀜 : 메시지와 사용자 정보를 끝까지 가지고 있어야 함
- 닉넴 중복 허용
- record를 총 두 번 탐색해, 첫 탐색에서 user id 별 최종 닉네임을 탐색하고, 두 번째 탐색에서 메시지를 출력한다.
- O(2N)으로 해결 가능하다. (startswith(str)는 앞에서부터 str 만큼만 비교하므로 상수 시간으로 계산)
풀이 완료 : 2023-09-19 10:55 (풀이 시간 : 15분 소요)
테스트 1 〉 | 통과 (0.02ms, 10.4MB)
-- | --
테스트 2 〉 | 통과 (0.01ms, 10.5MB)
테스트 3 〉 | 통과 (0.07ms, 10.4MB)
테스트 4 〉 | 통과 (0.04ms, 10.6MB)
테스트 5 〉 | 통과 (0.97ms, 10.7MB)
테스트 6 〉 | 통과 (0.76ms, 10.6MB)
테스트 7 〉 | 통과 (0.59ms, 10.9MB)
테스트 8 〉 | 통과 (0.73ms, 10.8MB)
테스트 9 〉 | 통과 (1.35ms, 10.8MB)
테스트 10 〉 | 통과 (0.83ms, 10.8MB)
테스트 11 〉 | 통과 (0.45ms, 10.6MB)
테스트 12 〉 | 통과 (0.45ms, 10.6MB)
테스트 13 〉 | 통과 (0.70ms, 10.8MB)
테스트 14 〉 | 통과 (0.90ms, 11MB)
테스트 15 〉 | 통과 …

[2023-09-20] jisu #239

---

Programmers/땅따먹기/wooyeol.py

땅따먹기
https://school.programmers.co.kr/learn/courses/30/lessons/12913
풀이시간 
19:09 ~ 19:18 / 19:40 ~ 20:20 (49분)
문제 조건
행의 개수(N) : 100,000 이하의 자연수
열의 개수 : 4개
점수 : 최대 100이하의 자연수
시간 복잡도 : 
O(N * (4 * 3 * 3) + 4) = O(N)
접근법
무슨 알고리즘으로 풀이 할 수 있을까? -> DP
- 현재 행의 자기 열의 값에 이전 행의 자신의 열을 제외한 나머지 열들의 최대 값을 현재 열에 더해주기
dp 테이블은 현재 행의 자신의 열중 최댓값을 기록

[2023-09-20] wooyeol #238

---

Programmers/오픈채팅방/wooyeol.py

오픈채팅방
https://school.programmers.co.kr/learn/courses/30/lessons/42888
풀이시간 
20 : 48 ~ 21 : 03 (15분)
문제 조건
1 <= record(R) <= 100,000
시간 복잡도 : 
O(R + R) = O(R)
접근법
무슨 알고리즘으로 풀이 할 수 있을까? -> 시뮬레이션
- 문제 내용에 따라 uid 저장 테이블과 들어오고 나올 때를 records에 기록하여 최종적 변경된 닉네임으로 채팅 서비스 기록 남기기

[2023-09-20] wooyeol #239

---

Programmers/방문 길이/jisu.py

풀이 시작 : 2023-09-20 10:24
- 수동 BFS..?
- 이동하면서 matrix에다가 방문 체크를 하고, matrix 범위 내 방문 체크가 안되어있는 곳을 밟을 때 카운트
- -5~5범위를 -> 0 ~ 10로 대체
- 주의할 점
- 특정 점을 새로 방문했는지의 여부가 아닌, 그 길을 처음 갔는지에 대해서이다.
- 좌표 별 어디서 그 좌표에 도달했는지 set으로 관리한다.
- (0, 0) -> (1, 1)로 갔다면 (1, 1)의 set에 (0, 0)을 add
- 이때 (1, 1) -> (0, 0)도 같은 길이므로 (0, 0)의 set에 (1, 1)도 add
풀이 완료 : 2023-09-20 10:49 (풀이 시간 : 25분)
테스트 1 〉 | 통과 (0.09ms, 10.3MB)
-- | --
테스트 2 〉 | 통과 (0.05ms, 10.3MB)
테스트 3 〉 | 통과 (0.03ms, 10.2MB)
테스트 4 〉 | 통과 (0.12ms, 10.2MB)
테스트 5 〉 | 통과 (0.15ms, 10.2MB)
테스트 6 〉 | 통과 (0.06ms, 10.2MB)
테스트 7 〉 | 통과 (0.06ms, 10.3MB)
테스트 8 〉 | 통과 (0.06ms, 10.3MB)
테스트 9 〉 | 통과 (0.04ms, 10.1MB)
테스트 10 〉 | 통과 (0.09ms, 10.3MB)
테스트 11 〉 | 통과 (0.05ms, 10.2MB)
테스트 12 〉 | 통과 (0.13ms, 10.2MB)
테스트 13 〉 | 통과 (0.12ms, 10.4MB)
테스트 14 〉 | 통과 (0.13ms, 10.2MB)
테스트 15 …

[2023-09-22] jisu #240

---

Programmers/방문 길이/dohyun.py

풀이시간
- 약 30분
접근법
- visit 배열을 활용하여 풀이 가능
- dirs < 500 으로 시간복잡도도 충분
- visit 딕셔너리의 키는 좌표와 좌표간의 연결
회고
- 모든 좌표간의 연결을 저장할 필요 없이 인접 좌표와의 연결만 표현하면 되므로 메모리 낭비
- 다 풀고나서 visit 배열을 다시 정의해서 풀이
- #240

[2023-09-22] dohyun #240

---

BOJ/예산/jisu.py

풀이 시작 : 2023-09-24 14:02
- 3 <= N <= 10,000, 각 수는 1이상 100,000 이하이다.
- 지방의 수와 예산을 계산하는 부분에 대한 알고리즘을 O(NlogN)으로 설계해야 한다.
- 예산의 상한을 maximum으로 하고, 배정 가능한 최대 maximum을 구하면 된다.
- 상한으로 가능한 범위는 low, high = 0, max(requests)
- 이분 탐색으로 upperbound(예산을 배정 가능한 최대 maximum)를 구하면 된다.
- upperbound를 구했으면 이를 적용해서 배정한 최대 예산을 출력한다.
- maximum 탐색(이분탐색) + 예산 배정 가능 여부 = O(logN) * O(N) = O(NlogN)
- maximum 확정 후 최대 예산 탐색 = O(N)
풀이 완료 : 2023-09-24 14:12 (풀이 시간 : 10분 소요)
메모리 | 32276KB
-- | --
시간 | 72ms

[2023-09-25] jisu #267

---

BOJ/공유기 설치/wooyeol.py

공유기 설치
https://www.acmicpc.net/problem/2110
풀이시간 
00 : 25 ~ 01 : 20 (55분)
문제 조건
2 <= N <= 200,000
2 <= C <= N
0 <= x <= 1,000,000,000
시간 복잡도 : 
O(NlogN + logx * N)
접근법
무슨 알고리즘으로 풀이 할 수 있을까? -> 이진 탐색
절대 이진 탐색을 떠올릴 수 없는 문제 설명이지만 과거 풀었던 기억을 통해서 문제를 풀이하였습니다.
(일단 문제 설명이 너무 이상합니다. 가장 인접한 두 공유기 사이의 거리를 최대로... 화가 납니다. 내 자소서가 나을듯)
1,000,000,000(10억)이 탐색해야할 영역이기 때문에 logN으로 풀이를 해야하고 이진 탐색을 사용하여 최단 거리를 찾아낼 수 있습니다.

[2023-09-25] wooyeol #266

---

BOJ/예산/wooyeol.py

예산
https://www.acmicpc.net/problem/2512
풀이시간 
10 : 20 ~ 10 : 32 (12분)
문제 조건
3 <= N <= 10,000
1 <= x <= 100,000
시간 복잡도 : 
O(N + logx * N)
접근법
무슨 알고리즘으로 풀이 할 수 있을까? -> 이진 탐색
목표하는 상한액을 찾기 위해서 1 ~ 100,000안의 값을 찾아야 하기 때문에 이진 탐색을 통해서 탐색합니다.

[2023-09-25] wooyeol #267

---

BOJ/예산/dohyun.py

풀이시간
- 약 30분
접근법
- N이 1만이하 -> O(NlogN) 쯤의 복잡도로 해결해야함
- 특정 값과 비교해서 조건을 오바하면 줄이기, 조건보다 부족하면 늘리기 + O(NlogN)? -> 이진탐색
회고
- 순간 헷갈려서 시작점을 예산요청의 최소값으로 설정하니 특정 케이스(47%)에서 에러가 계속 발생했음
- 1로 설정하여 해결 -> 이것때메 버벅이느라 시간 낭비 ㅠㅠ
- #267

[2023-09-25] dohyun #267

---

BOJ/List of Unique Numbers/dohyun.py

풀이시간
- 약 1시간
접근법
- N 십만 이하 -> O(NlogN)
- 연속된 수의 개수를 1개, 2개, ... , N 개 뽑기, 최소값은 연속한 1개의 수를 뽑았을 때 -> N
- 이를 투포인터로 구현 가능
- 집합 자료형을 통해 고유값만을 갖는 수열을 구해놓고, 해당 수열의 길이만큼 빼주면 됨
- ex: [1,2,3,4,5]
- cnt += end - start (5-0 = 5)
- tmp_set = [1,2,3,4,5] -> [1], [1,2], [1,2,3], [1,2,3,4], [1,2,3,4,5] (cnt 개수 = 경우의 수)
- 이후에 start 포인트를 제거 -> tmp_set = [2,3,4,5]
- cnt += end - start (5-1 = 4)
- tmp_set = [2,3,4,5] -> [2], [2,3], [2,3,4], [2,3,4,5]
- ...
- cnt += end - start (5-4 = 1)
- tmp_set = [5] -> [5]
- start 포인트 제거 -> tmp_set = []
- cnt += end - start (5-5 = 0)
- 종료
회고
- 좀 더 많이 푸는 연습을 해서 버벅거리는 시간 줄이기
- #269

[2023-09-27] dohyun #269

---

BOJ/List of Unique Numbers/sumin.py

**풀이시간**: 30분
**\<input>**
n : 수열의 길이 (1 ≤ N ≤ 100,000)
s : 수열 (1 ≤ 원소 ≤ 100,000)
투포인터를 통해 연속된 부분 수열을 만들 수 있다.
수를 하나씩 확인하며 딕셔너리에 해당 숫자가 마지막으로 나온 인덱스를 보관해 중복되지 않은 부분 수열을 만든다.
예를 들어, [1, 2, 3, 2, 1]이라는 수열이 있을 때
각 수를 탐색하며 아직 나오지 않은 수라면 딕셔너리에 해당 수의 인덱스를 추가해준다.
이전에 등장한 적이 있고, 딕셔너리에 저장된 인덱스값이 left 보다 크다면 left 인덱스를 1 증가시켜서 이전에 등장한 수의 인덱스보다 한 칸 오른쪽으로 이동한다.   
left = 0, right = 0 -> {1: 0}, ans = 1   
left = 0, right = 1 -> {1: 0, 2: 1}, ans = 1 + 2   
left = 0, right = 2 -> {1: 0, 2: 1, 3: 2}, ans = 1 + 2 + 3   
left = 2, right = 3 -> {1: 0, 2: 3, 3: 2}, ans = 1 + 2 + 3 + 2  
left = 2, right = 4 -> {1: 4, 2: 3, 3: 2}, ans = 1 + 2 + 3 + 2 + 3  
**<시간복잡도>**
`O(n)`

[2023-09-27] sumin #269

---

BOJ/가장 긴 짝수 연속한 부분 수열 (large)/wooyeol.py

가장 긴 짝수 연속한 부분 수열 (large)
https://www.acmicpc.net/problem/22862
풀이시간
21:53 ~ 22 : 50 (57분)
문제조건
1 <= N <= 1,000,000
1 <= K <= 100,000
1 <= x <= 10^6
시간 복잡도
O(N + K + N) : O(N)
접근법
무슨 알고리즘으로 풀이 할 수 있을까? 시뮬레이션 + 최적화
예외처리 : 만약 K가 N-1보다 크다면 모든 짝수를 가지는 부분 수열의 합과 같다.
1. 연속된 짝수를 가지는 부분 수열의 원소 개수 구하기 O(N)
1 2 3 4 5 6 7 8
[0, 1, 1, 1, 1]
1 2 3 4 5 5 6 8
[0, 1, 1, 0, 2]
2 4 6 8 8 6
[6]
2 1 3 2 4 8
[1, 0, 3]
2. K만큼 슬라이딩하며 데이터를 더해서 Max 값을 갱신 (리스트의 원소를 슬라이딩하는 과정을 최적화)

[2023-09-27] wooyeol #268

---

BOJ/List of Unique Numbers/wooyeol.py

List of Unique Numbers
https://www.acmicpc.net/problem/13144
풀이시간
23 : 02 ~ 23:24 / 23: 50 ~ 31 (풀이 실패)
풀이 참고
https://eunbin00.tistory.com/163
문제조건
1 <= N <= 100,000
1 <= x <= 100,000
시간 복잡도
접근법
무슨 알고리즘으로 풀이 할 수 있을까? 투 포인터
각 요소를 하나씩 검사하며 중복이 발생하면 start 조정, 중복이 발생하지 않으면 start 조정
1. End 위치의 값이 중복이 아닐 경우
- End 위치의 값이 사용됨을 알리고
- End를 증가시켜 다음 숫자 확인
- 증가된 수열을 기준으로 가능한 부분 수열 갯수 추가하기 -> 어떻게 사람의 머리에서 이런게 나올 수 있죠...?
ex) 5   
1 2 3 1 2
[1]
1 - [1]
[1, 2]
2 - [2],[1,2]
[1, 2, 3]
3 - [3],[2,3][1,2,3]
[2, 3, 1]
3 - [1],[3,1],[2,3,1]
[3, 1, 2]
3 - [2],[1,2],[3,1,2]
[1],[2],[3],[1],[2]
[1,2][2,3],[3,1][1,2]
[1,2,3],[2,3,1][3,1,2]
2. End 위치의 값이 중복일 경우
- Start 위치의 값을 사용되지 않음으로 알리고
- Start를 증가시켜 범위 조정

[2023-09-27] wooyeol #269

---

BOJ/싸이버개강총회/dohyun.py

풀이시간
- 약 15분
접근법
- 채팅 기록은 10만 이하 -> O(NlogN)
- HH:MM 단위를 분 단위로 변환하면 편리할듯함
- 채팅 기록이 몇 개인지 입력으로 안 주어진다..?
- try except 으로 수동 처리
- 시간은 정렬되어 입력되므로, 퇴근 시 출근 기록이 있는지 확인해야함
- 즉 in, not in 연산 필요 -> set 자료형 사용하여 시간복잡도 개선
회고
- set 을 자주 활용하다보니 어려움없이 풀어낼 수 있었음!
- #270

[2023-09-29] dohyun #270

---

BOJ/문자열 지옥에 빠진 호석/dohyun.py

풀이시간
- 약 1시간 풀이 후 실패로 답지 참조
접근법
- BFS 로 한번 탐색해보자
- 각 선호 문자열마다 BFS 를 돌리면 너무 오래 걸림
- 한번의 bfs 에 문자열 배열을 저장해놓고 선호 문자열이 존재하는지 여부를 조사하는 것이 나을듯
- 답지 풀이
- BFS/DFS 둘 다 사용해도 상관없는듯 함
- 본 풀이에서는 재귀로 구현이 편리한 DFS 활용
- visit 배열이 아닌 딕셔너리를 활용
- key: 문자열, value: 해당 문자열이 나올 수 있는 경우의수
- 조건문이 아닌 나머지 연산을 활용하여 범위를 넘어간 DFS 를 구현
회고
- 하 문제 길ㄷㅏ ... 집중력이 많이 부족해서 놓친 부분이 꽤 있었음 (ex: 신이 좋아하는 문자열의 길이는 5이하 조건)
- #271

[2023-09-29] dohyun #271

---

BOJ/문자열 지옥에 빠진 호석/jisu.py

풀이 시작 : 2023-09-28 17:22
신이 좋아하는 문자열의 길이를 N이라고 할 때
- matrix는 최대 10 x 10
- K <= 1000
- 문자열 길이 : 1 <= N <= 5
- 복잡도 최대 : 10 x 10 x 1000 x 5 = 5,000,000
- (결과론) 완탐 가능할 것 같지만, dfs 돌릴 때 백트래킹 안하면 시간초과!
- 알파벳 N이 될 때까지 각 이동마다 재귀해서 문자열이랑 같은 경우 카운트하면 될듯!
- 대신 다시 방문하는 걸 허용하니 visited 필요 없음
- target이 중복으로 주어질 수 있으므로 target에 대한 dict 만들어서 해 저장해놓기
- dfs 과정에서 완탐은 안되고, 백트래킹 수행해야 함! 다음 탐색해야할 문자열이 같을 때만 가지 뻗기
- 46번 라인의 조건문은 없어도 될 것 같은데, 없으면 전체 통과가 안됨(2/16)
- 다음 문자가 같을 때만 가지를 뻗으니까.. 되어야 하는데.. 외 안되?
- 의문 해결! 처음 재귀 시작할 때에도 같을 때만 재귀하도록 해줘야 했음! (수정 완료)
풀이 완료 : 2023-09-28 17:49(풀이 시간 : 27분 소요)
메모리 | 시간
-- | --
31256KB | 580ms

[2023-09-29 jisu #271

---

Programmers/스킬트리/jisu.py

풀이 시작 : 2023-10-01 16:07
- 문자열의 길이 <= 26
- 리스트의 길이 <= 20
- 26 * 20 = 5200, 한 번의 순회에서 모든 문자열의 문자를 순회하는 것은 괜찮음
- 스킬트리에서 가능한 개수를 세면 됨
- 선행 스킬이 있는 스킬의 경우, 선행 스킬을 배웠는지의 여부를 판단하면 됨
- A -> B -> C 일 때 C에 대해서 B여부만 판단하면 됨 (어차피 A를 안배우면 B를 못배우기 때문)
풀이 완료 : 2023-10-01 16:22 (풀이 시간 : 15분 소요)

[2023-10-02] jisu #297

---

Programmers/스킬트리/dohyun.py

풀이시간
- 약 15분
접근법
- 시간복잡도 충분
- 선행 스킬이 필요함 -> 큐로 구현 가능!
회고
- 시간복잡도를 고려할 필요가 없었기 떄문에 비교적 수월하게 풀이
- 스택으로도 풀 수 있을것 같긴한데 큐가 선행스킬을 먼저 찍는다는 점에서 직관적으로 다가왔음
- 예외 케이스(25 라인)의 경우 조금 더 최적화 해낼 수 있을듯함
- 여러분들의 코드를 열심히 공부하겠습니다!!!
- #297

[2023-10-02] dohyun #297

---

Programmers/스킬트리/sumin.py

**풀이시간**: 30분
**\<input>**
skill: 선행 스킬 순서(알파벳 대문자)
- 1이상 26이하로 중복해서 주어지지 않음
스킬트리: 유저들이 만든 스킬트리
- 1 이상 20이하인 배열
- 각 원소는 길이가 2 이상 26인 문자열로, 스킬은 중복해서 주어지지 않음
skill_tree를 하나씩 순회하며 해당 스킬트리가 가능한지 확인한다.
1) skill_tree의 스킬을 하나씩 확인하면서 선행스킬에 포함되는 스킬만 뽑아 문자열로 만든다.
2) 위에서 만든 스킬 문자열이 선행 스킬의 순서에 해당되는지 확인한다.
- 여기서 선행스킬에 해당되는게 하나도 없을 때도 카운트 돼야한다. (이 부분을 놓쳐서 오래걸림..)
- ex) skill = "CBD", skill_trees = ["AF"] -> 1
**<시간복잡도>**
`O(len(skill_trees) * len(skill_tree))`
최대 연산횟수는 20 * 26 = 520

[2023-10-02] sumin #297

---

Programmers/프렌즈4블록/wooyeol.py

프렌즈4블록
https://school.programmers.co.kr/learn/courses/30/lessons/17679
풀이시간 
15:12 ~ 16:02 (50분)
문제 조건
높이 M, 폭 N
2<= n,m <= 30
시간 복잡도 :
O((N * M * 3) + (N * M) + (N * 2M))
O(N * M)
접근법
무슨 알고리즘으로 풀이 할 수 있을까? -> 시뮬레이션
- 삭제 연산을 진행하였을 때 기억되는 주소값이 하나도 없다면 업데이트가 불가능한 상황이므로 종료
1. 4칸씩 삭제되는 주소 값 기억하기
- 바로 삭제하면 동시에 적용되는 칸들이 생략될 수 있기 때문에
2. 기억된 주소값을 모두 "-"으로 변경하기 (삭제 연산)
3.  "-"로 표기된 Col을 가장 상단으로 올리기
- 각 Column 별로 "-"의 개수를 카운트하고 가장 상단에서부터 "-"를 채우기
- 이후 deque에 기억된 알파벳 순서대로 배치

[2023-10-06] wooyeol #300

---

Programmers/롤케이크 자르기/wooyeol.py

롤케이크 자르기
https://school.programmers.co.kr/learn/courses/30/lessons/132265
풀이시간 
16:28 ~ 17:07 (46분)
23:39 ~ 23:46
문제 조건
1 <= len(topping) <= 1,000,000
시간 복잡도 :
O(T + T) = O(2,000,000)
접근법
무슨 알고리즘으로 풀이 할 수 있을까? -> dictionary
- 토핑을 하나씩 검사하며 동생의 조각에 추가하고 나의 조각에서 제거하기
- 이때에 토핑 종류가 사라졌는지 여부를 확인
1. 동생의 조각에 현재 토핑 추가
2. 나의 조각에 현재 토핑 제거
- 토핑이 사라졌을 경우 현재 토핑 완전히 제거
- 현재 토핑의 종류의 개수를 확인하여
- 나와 동생의 토핑이 같다면 정답 개수 추가
- 동생의 토핑이 더 커졌다면 break

[2023-10-06] wooyeol #301

---

Softeer/순서대로 방문하기/wooyeol.py

순서대로 방문하기
https://softeer.ai/practice/info.do?idx=1&eid=2050
풀이시간 
22:08 ~ 22:50 (42분)
문제 조건
[조건 1] 2 ≤ n ≤ 4
[조건 2] 2 ≤ m ≤ n**2
시간 복잡도 :
O(4**(n**2))
접근법
무슨 알고리즘으로 풀이 할 수 있을까? -> 백 트래킹
가능한 모든 경우를 계산하기 위해서는 백 트래킹을 통해서 가능한 방법을 모두 확인하는 것이 필요하겠다고 생각했습니다.
1. table을 입력받고 block들을 입력받을 때는 0 인덱스가 시작지점이 될 수 있게 Lambda를 통해 좌표 형식을 통일합니다.
2. 초기값 세팅을 위해서 시작 지점 세팅 및 시작 지점 방문 처리를 진행합니다.
3. backtracking 진행
1. 종료 컨디션 지정 : block의 인덱스와 m이 같아지면 모든 block을 방문했기 때문에 종료
2. 4방향에 대해서 좌표값이 유효한지 벽 혹은 방문한 좌표가 아닌지 검사합니다.
- 이상이 없다면 백트래킹을 위해 방문 처리를 진행하고 다시 재귀문을 통해서 현재 좌표가 현재 지나가야하는 
좌표와 같다면 block 인덱스 증가 후 백 트래킹 진행 아니라면 인덱스 증가 없이 백 트래킹 진행
4. 전체 answer를 반환합니다.

[2023-10-09] wooyeol #313

---

Softeer/자동차 테스트/dohyun.py

풀이시간
- 10분
접근법
- n 5만 이하 -> 대충 O(NlogN)
- 3대의 자동차를 고르는것이 고정
- 중앙값이 존재하지 않으면 0
- 존재하면 경우의 수는 (중앙값보다 작은 값의 수) x (중앙값보다 큰 값의 수)
- 즉 해당 값이 존재하는지 탐색하고, 존재한다면 인덱스를 잘 활용하면 됨 -> 이진탐색
회고
- 3개의 값을 선택, 중앙값이라는 힌트로 이진탐색을 쉽게 눈치챌 수 있었음
- #312

[2023-10-09] dohyun #312

---

Softeer/순서대로 방문하기/dohyun.py

풀이시간
- 약 1시간 풀이 후 실패로 답지 참조
접근법
- 주어진 변수의 범위가 굉장히 좁음 -> 구현에 집중
- 특정 조건이 있는 그래프 탐색 -> 백트래킹
- visit 배열을 초기화하는 작업이 필요
회고
- 인덱스로 goals 좌표 접근하는 방식 익숙해지기
- #313

[2023-10-09] dohyun #313
